INSERT INTO `data` VALUES (81, 22, '所謂第三代電腦，是以何種零件為主要零件? ', '電晶體 ', '積體電路 ', '真空管 ', '超大型積體電路', '', '2');
INSERT INTO `data` VALUES (82, 22, '依據電子計算機的演進過程，下列順序那一項為正確? ', '積體電路 ', '大型積體電路 ', '電晶體 ', '真空管', '', '3');
INSERT INTO `data` VALUES (83, 22, '年代ENIAC所用的主要元件是 ', '積體電路 ', '電晶體 ', '真空管 ', '以上皆非', '', '3');
INSERT INTO `data` VALUES (84, 22, '年代ENIAC所用的主要元件是 ', '積體電路 ', '電晶體 ', '真空管 ', '以上皆非', '', '3');
INSERT INTO `data` VALUES (85, 22, '所謂第四代電腦是以何種電子元件為主要零件? ', '真空管 ', '積體電路 ', '電晶體 ', '超大型積體電路', '', '4');
INSERT INTO `data` VALUES (86, 22, '電子計算機問世至今，經歷三、四十年其間新型電腦不斷推陳出新，不管怎麼新，依舊保有"內存程式"的觀念，    最先提出這種觀念的是 ', '巴貝基 ', '范紐曼 ', '巴斯卡 ', '貝爾', '', '2');
INSERT INTO `data` VALUES (87, 22, '針對電腦未來的發展，下列敘述何者是錯誤? ', '速度愈來愈快 ', '記憶容量愈來愈大    ', '體積愈來愈大 ', '價格愈來愈便宜', '', '3');
INSERT INTO `data` VALUES (88, 22, '下列何者不是電子計算機的特性? ', '高速的運算 ', '可預存程式 ', '會自動做判斷 ', '準確性高下列何者不為電子計算機的特性? ', '準確性高 ', '3');
INSERT INTO `data` VALUES (89, 22, 'C  .在一般計算機分類下，下列何者屬於軟體? ', '中央處理單元(CPU) ', '鍵盤 ', '磁碟作業系統(DOS)    ', '隨機存取記憶體(RAM) ', '印表機', '3');
INSERT INTO `data` VALUES (90, 22, '週邊設備(例如鍵盤、滑鼠、掃瞄器等)是屬於 ', '硬體 ', '軟體 ', '韌體 ', '記憶體', '', '3');
INSERT INTO `data` VALUES (91, 22, '在計算機中將某一部份軟體永恆的存在唯讀記憶體中，我們稱之為 ', '韌體 ', '軟體 ', '輔助記憶體 ', '硬體', '', '1');
INSERT INTO `data` VALUES (92, 22, '用來處理連續性資料的計算機，稱為何種型態之計算機? ', '數位 ', '類比 ', '混合 ', '通用', '', '2');
INSERT INTO `data` VALUES (93, 22, '一般在學校教學所用的個人電腦(PC)是屬於那一類型電腦 ', '特殊用途型 ', '類比型 ', '超大型 ', '數位型 ', '混合型', '4');
INSERT INTO `data` VALUES (94, 22, '下列有關數位電腦的敘述，何者有誤? ', '輸入及輸出之資料，均以數位型態來表示 ', '數位電腦處理資料之速度    比類比電腦慢 ', '數位電腦處理資料之速度比類比電腦快 ', '數位電腦處理資料之準確度比類比電腦高', '', '3');
INSERT INTO `data` VALUES (95, 23, '以下何者不是圖像設計的基本概念?', '一致的影像格式', '強調重要的細節', '對稱平衡', '黃金比例', '', '1');
INSERT INTO `data` VALUES (96, 23, '導覽系統應該', '設計直覺並且保持一致性', '必須是下拉式選單的形式', '不必使用視覺回饋', '不佔用版面空間', '', '1');
INSERT INTO `data` VALUES (97, 23, '底下那一種素材需要先取得使用權才能運用在專案中?', 'Youtube網站上的視訊影片', '從CD唱片上轉錄一段音樂', '唐詩中的某一句', '引用某部落格上的一段話', '', '3');
INSERT INTO `data` VALUES (98, 23, '網站的分鏡腳本(storyboard)不應該有哪一個選項?', '網頁文件的標題', '連結目標的網頁', '目標群眾說明', '導覽列的位置', '', '3');
INSERT INTO `data` VALUES (99, 23, '下列何者受到著作權的保護?', '腦海中的新創意', '尚未公諸於世的新作品', '已經發表的作品', '尚未公開以及發表的作品', '', '4');
INSERT INTO `data` VALUES (100, 23, '以口述方式紀錄他人的小說著作，並在網路上無償分享給所有人：', '符合合理使用範圍', '屬於衍生著作(亦稱為"改作著作")', '侵犯原作者的著作權(公開口述權)', '沒有涉及營利，所以沒有侵權', '', '3');
INSERT INTO `data` VALUES (101, 23, '提高網站的易用性的好處不包含底下哪一項?', '可以提高網站在搜尋引擎的排名', '聚集更多使用者', '容易管理與維護', '豐富網頁內容', '', '4');
INSERT INTO `data` VALUES (102, 23, '若要把Flash內容崁入網頁，最好會出哪一種格式?', 'png', 'gif', 'swf', 'fla', '', '3');
INSERT INTO `data` VALUES (103, 23, '哪一個不是影響Flash影片播放順暢與否的因素?', '使用者的電腦速度', '畫面的複雜度', '影片檔的大小', '影片時間的長度', '', '4');
INSERT INTO `data` VALUES (104, 23, 'Flash的預設視訊影片格式的附檔名為哪一種?', '.mov', '.wmv', '.flv', '.mpg', '', '3');
INSERT INTO `data` VALUES (105, 23, '放在「貼板上」區域的圖像，在預設情況下：', '不會顯示在舞台區域，也不會被包含在.swf檔案中', '不會顯示在舞台區域，但是會被包含在.swf檔案中', '會顯示在舞台區域，也會被包含在.swf檔案中', '會顯示在舞台區域，但不會包含在.swf檔案中', '', '2');
INSERT INTO `data` VALUES (106, 23, '假設畫面上有個物件繪圖模式繪製，包含填色內容的圖形，底下哪兩項敘述是正確的?', '可以使用「選取」工具改變他的外觀', '使用「選取」工具點選此圖形內容時，將只有填色內容被選取到', '使用「選取細部」工具點選此圖形，不可透過錨點及控制線作細部調整', '使用「套索」工具框選部分圖形時，只有被框選的部分會被選取', '', '1');
INSERT INTO `data` VALUES (107, 23, '關於鉛筆工具的描述，哪一項是錯的：', '只有在「直線下」模式之下，形狀辨識功能才會有作用', '可以使用漸層填色', '使用「墨水」模式繪圖，線條裡的控制錨點會比較多', '線條的粗細不能超過10.0', '', '4');
INSERT INTO `data` VALUES (108, 23, '下列何者是「基本矩形工具」的特性', '用來調整錨點及控制線', '可任意調整圓角', '用來繪製精確的圖像', '繪製後不能輕易修改圓角', '', '2');
INSERT INTO `data` VALUES (109, 23, '選取細部工具可以用來', '顯示被選取造形的錨點', '刪除錨點', '增加錨點', '可以任意調整圓角', '', '1');
INSERT INTO `data` VALUES (110, 23, '哪一項工具被用來選取圖像的任意部分', '魔術棒工具', '套索工具', '選取工具', '選取細部工具', '', '2');
INSERT INTO `data` VALUES (111, 23, '建立文字欄位時，若要讓欄位內容自動換行，必須要?', '選取「文字工具」後，在舞台上按移下滑鼠左鍵來建立欄位', '選取「文字工具」後，在舞台上按著滑鼠左鍵不放並向右脫一來建立欄位', '將文字欄位的「字行類型」屬性，設成「多行」', '加大字元間距', '', '2');
INSERT INTO `data` VALUES (112, 23, '假設要在舞台的傳統文字欄位上設定一個像x2這樣的上標字內容，底下哪一個概念是正確的?', '在動態文字欄位上要設定顯示外框', '可以使用裝置字體', '要取消屬性檢測器的「可選取的」選項', '在輸入文字欄位上要嵌入字體', '', '3');
INSERT INTO `data` VALUES (113, 23, '關於採用文字工具建立的文字欄位，哪一項描述是正確的', '只有靜態文字欄位可以更改文字方向', '只有靜態文字欄位不可設定上標或下標字', '只有靜態文字欄位可以使用裝置字體', '只有靜態文字欄位可以設定超連結', '', '1');
INSERT INTO `data` VALUES (114, 23, 'Flash具有哪一種文字引擎', '動態文字', '靜態文字', '傳統文字', '輸入文字', '', '3');
INSERT INTO `data` VALUES (115, 23, 'TLF文字引擎不包含哪一個類型設定', '靜態的', '唯讀', '可選取的', '可編輯的', '', '1');
INSERT INTO `data` VALUES (116, 23, '底下哪一種方式可以避免圖像或線條彼此分割?', '畫圖時，啟動「物件模式」', '把圖像放在不同的圖層', '把畫好的圖像變成群組', '使用「鋼筆」工具畫圖', '', '4');
INSERT INTO `data` VALUES (117, 23, '若要匯入包含去背(背景透明)的點陣影像，可以使用', '.psd', '.exe', '.jpg', '.dxf', '', '1');
INSERT INTO `data` VALUES (118, 23, '遮色片定義了', '主動區域', '可被看見的區域', '邊界的色彩', '舞台的邊界', '', '2');
INSERT INTO `data` VALUES (119, 23, '下列哪個選項與影格相符合', '代表該時間點，圖層沒有畫面', '代表該時間點，動畫元素的某些參數值改變了', '代表該時間點圖層是否有畫面', '代表該時間點，圖層畫面有變動', '', '3');
INSERT INTO `data` VALUES (120, 23, '下列哪個選項與關鍵影格相符合', '代表該時間點，圖層沒有畫面', '代表該時間點，動畫元素的某些參數值改變了', '代表該時間點圖層是否有畫面', '代表該時間點，圖層畫面有變動', '', '4');
INSERT INTO `data` VALUES (121, 23, '下列哪個選項與空白關鍵影格相符合', '代表該時間點，圖層沒有畫面', '代表該時間點，動畫元素的某些參數值改變了', '代表該時間點圖層是否有畫面', '代表該時間點，圖層畫面有變動', '', '1');
INSERT INTO `data` VALUES (122, 23, '下列哪個選項與屬性關鍵影格相符合', '代表該時間點，圖層沒有畫面', '代表該時間點，動畫元素的某些參數值改變了', '代表該時間點圖層是否有畫面', '代表該時間點，圖層畫面有變動', '', '2');
INSERT INTO `data` VALUES (123, 23, '以下哪一種物件，無法套用「移動補間」動畫?', '使用物件繪圖模式繪製的圖像', '不是用物件繪圖模式繪製的圖像', '群組圖像', '文字欄位', '', '2');
INSERT INTO `data` VALUES (124, 23, '底下關於物件繪製模式的描述，哪一項是正確的?', '圖像彼此不會分割', '無法直接修改形狀與顏色', '等同於「群組」物件', '可用於建立形狀補間動畫', '', '1');
INSERT INTO `data` VALUES (125, 23, '底下哪兩種方式可以延長動畫的播放時間?', '插入關鍵影格', '插入空白關鍵影格', '插入影格', '增加影格速率', '', '3');
INSERT INTO `data` VALUES (126, 23, '如何縮減發布的Flash影片的大小?', '盡可能重複使用元件', '改變圖層的載入順序', '多使用點陣圖而非向量圖', '嵌入所有文字', '', '1');
INSERT INTO `data` VALUES (127, 23, 'Flash預設沒有哪一種元件?', '點陣圖', '按鈕', '圖像', '影片片段', '', '1');
INSERT INTO `data` VALUES (128, 23, '影片中採用元件下哪何者不是好處?', '易於維護和編輯', '減少檔案大小', '在不同的專案分享(共用)', '允許使用嵌入字體', '', '4');
INSERT INTO `data` VALUES (129, 23, '在某個按鈕上按著滑鼠扭不放，再將滑鼠移開按鈕範圍，此時，按鈕將呈現哪個狀態的畫面?', '一般', '滑入', '滑出', '按下', '', '1');
INSERT INTO `data` VALUES (130, 23, '當游標滑入某個按紐時，若要讓按鈕本身產生循環的動畫效果，可以：', '在「滑入」關鍵影格設定補間動畫', '在「滑入」關鍵影格設放置一個影片片段動畫', '在「滑入」關鍵影格設放置一個圖像動畫', '在「滑入」關鍵影格設放置一個按鈕', '', '2');
INSERT INTO `data` VALUES (131, 23, 'Flash的按鈕元件不包含底下哪些影格?', '一般', '滑入', '滑出', '按下', '', '3');
INSERT INTO `data` VALUES (132, 23, '哪一種類型的聲音必須等到全部載入完畢之後才能開始播放?', '串流', '靜態', '事件', '元件', '', '3');
INSERT INTO `data` VALUES (133, 23, '下列何者是Number的名詞解釋', '代表條件成立與否的true或false類型', '代表內容未定義', '可包含小數點的正負數字', '代表文字資料', '代表變數沒有值', '3');
INSERT INTO `data` VALUES (134, 23, '下列何者是Boolean的名詞解釋', '代表條件成立與否的true或false類型', '代表內容未定義', '可包含小數點的正負數字', '代表文字資料', '代表變數沒有值', '1');
INSERT INTO `data` VALUES (135, 23, '下列何者是String的名詞解釋', '代表條件成立與否的true或false類型', '代表內容未定義', '可包含小數點的正負數字', '代表文字資料', '代表變數沒有值', '4');
INSERT INTO `data` VALUES (136, 23, '下列何者是Undefined的名詞解釋', '代表條件成立與否的true或false類型', '代表內容未定義', '可包含小數點的正負數字', '代表文字資料', '代表變數沒有值', '2');
INSERT INTO `data` VALUES (137, 23, '下列何者是Null的名詞解釋', '代表條件成立與否的true或false類型', '代表內容未定義', '可包含小數點的正負數字', '代表文字資料', '代表變數沒有值', '5');
INSERT INTO `data` VALUES (138, 23, 'Flash不支援底下哪一個HTML標籤元素?', 'span', 'b', 'a', 'table', '', '4');
INSERT INTO `data` VALUES (139, 23, '底下哪一個是合法的物件實體名稱?', '7/24hr', '$user', 't-mc', 'var', '', '2');
INSERT INTO `data` VALUES (140, 23, '強制設定變數類型，下列何者不是好處?', '方便除錯成式', '編輯器可提供程式碼提示', '有助於格式化程式', '提升程式的執行效率', '', '3');
INSERT INTO `data` VALUES (141, 23, '底下的程式敘述執行之後，temp變數的值為何?var temp = 20;   temp  ="5";', '25', '205', '100', '20', '', '2');
INSERT INTO `data` VALUES (142, 23, 'ActionScript程式使用哪一種語法標示注解?', '//', '@', '#', '''', '', '1');
INSERT INTO `data` VALUES (143, 23, '「動作」面板的指令工具箱中，代表MovieClip(影片片段)的類別程式指令，放在哪個套件(package)中?', 'flash.movie', 'flash.media', 'flash.display', 'flash.net', '', '3');
INSERT INTO `data` VALUES (144, 23, '底下的程式碼執行之後，「輸出」版面將呈現?var score = 98 ;  trace(typeof score) ;', 'string', 'boolean', 'object', 'number', '', '4');
INSERT INTO `data` VALUES (145, 23, '底下哪一個滑鼠事件，代表「按一下」?', 'MouseEvent.RELEASE', 'MouseEvent.MOUSE_UP', 'MouseEvent.MOUSE_OVER', 'MouseEvent.MOUSE_WHEEL', 'MouseEvent.CLICK', '5');
INSERT INTO `data` VALUES (146, 23, '關鍵影格可設定「標籤文字」之外，還有哪一種設定選項?', '設定超聯結目標', '設定時間軸控制指令', '設定命名錨點，讓用戶透過瀏覽器的「上一頁」與「下一頁」紐，切換影片畫面', '設定影片的標題名稱', '', '3');
INSERT INTO `data` VALUES (147, 23, '影響視訊品質的不包含下列哪一項因素?', '影格畫面尺寸', '影格速率', '資料傳輸率限制', '選用的壓縮編解碼程式', '視訊檔的大小', '5');
INSERT INTO `data` VALUES (148, 23, '關於漸進式下載和串流播放的描述，底下何者有誤?', '串流播放需要透過特殊的影音伺服器軟體', '串流視訊不會暫存在用戶端', '漸進式下在必須完整下載之後，才能開始播放', '漸進式影片在下載過程中，無法任意跳轉', '', '3');
INSERT INTO `data` VALUES (149, 23, '關於外部.flv檔以及內嵌式視訊的.swf檔的描述，底下何者有誤?', '內嵌於.swf的視訊和.flv視訊檔，都不受到.swf的影格速率限制', '內嵌在.swf裡的視訊，會造成.swf檔案大小遽增', '外部的.flv比較便於替換視訊內容', '在不需要互動控制的情況下，內檻的視訊檔比較易於影片製作', '', '1');
INSERT INTO `data` VALUES (150, 23, '關於視訊影片裡的提示點(cue point)的描述，底下何者有誤?', '題式點紀錄了時間點與文字資訊', '在視訊播放過程中，可自動處發提示點事件', '強制視訊和.swf影片時間軸同步', '提示點資訊內嵌在.flv視訊裡面，而非外部檔', '', '3');
INSERT INTO `data` VALUES (151, 23, 'Flash 視訊檔和原始視訊檔的不同點是：', '原始視訊視經過壓縮後的Flash視訊影片', 'Flash視訊影片是經過壓縮後的視訊', 'Flash視訊檔比原始視訊檔還大', '', '', '2');
INSERT INTO `data` VALUES (152, 23, '底下哪個元素不能設定「輔助功能」?', '動態文字欄位', '影片片段元件', '按鈕元件', '圖像元件', '', '4');
INSERT INTO `data` VALUES (153, 23, '底下哪些輔助功能，是你在為視力受損的人是開發網站時，所不需考慮的?', '放大字體', '使用高度對比的色彩', '替影片加上字幕', '螢幕朗讀程式', '', '3');
INSERT INTO `data` VALUES (154, 23, '將Flash影片嵌入網頁時，需要用到哪一個標籤：', 'div', 'object', 'int', 'frame', '', '2');
INSERT INTO `data` VALUES (155, 23, '將Flash影片嵌入網頁時，需要用到哪一個標籤：', 'div', 'int', 'embed', 'frame', '', '3');
INSERT INTO `data` VALUES (156, 23, '在事件處理程式中，事件物件的target屬性的作用為何?', '代表處發事件的類型', '代表處發事件的來源物件', '代表事件物件的名稱', '代表處發事件的物件名稱', '', '2');
INSERT INTO `data` VALUES (157, 23, 'ActionScript 3.0 採用底下哪個指令，在舞台上動態放置物件?', 'addchild()', 'removeChild()', 'addEventListener()', 'removeEventlistener()', '', '1');
INSERT INTO `data` VALUES (158, 24, 'The production of Cats ______ for many years on Broadway.', ' cost  ', ' ran  ', ' dammed  ', ' soared				   ', '', '2');
INSERT INTO `data` VALUES (159, 24, 'The children were ______ by the death of both of their parents in the airplane crash.', ' healed  ', ' traumatized  ', ' reinforced  ', ' recurred				   ', '', '2');
INSERT INTO `data` VALUES (160, 24, 'He was filled with ______ after punishing his students in such a strict way.  ', ' remorse  ', ' humor  ', ' length  ', ' duty				   ', '', '1');
INSERT INTO `data` VALUES (161, 24, 'Many stray dogs were ______ at the park.  ', ' neglecting  ', ' shunning  ', ' lingering  ', ' counting				   ', '', '3');
INSERT INTO `data` VALUES (162, 24, 'The ______ actor and the supporting actress both won Oscars for their outstanding performances in that film.  ', ' secret  ', ' innocent  ', ' leading  ', ' deformed', '', '3');
INSERT INTO `data` VALUES (163, 24, 'Since their father was laid off, they have been living in ______. ', ' relationship  ', ' condition  ', ' giddiness  ', ' poverty				   ', '', '4');
INSERT INTO `data` VALUES (164, 24, 'The territory of Japan ______ from Hokkaido in the north to the Kyushu Islands in the south.  ', ' scars  ', ' extends  ', ' verifies  ', ' fastens				   ', '', '2');
INSERT INTO `data` VALUES (165, 24, 'The upscale Chinese dish "fish-fin soup" leads to cruel shark ______.', ' murder  ', ' slaughter  ', ' suicide  ', ' mercy-killing				   ', '', '2');
INSERT INTO `data` VALUES (166, 24, 'The soldiers raised the flag high up the ______ and everyone saluted. ', ' role  ', ' pole  ', ' roll  ', ' poll				   ', '', '2');
INSERT INTO `data` VALUES (167, 24, 'The villagers complained about the government''s ______ of environmental protection, which has led to the serious pollution of their drinking water.', 'neglect  ', ' resolution  ', ' remorse  ', ' persevere', '', '1');
INSERT INTO `data` VALUES (168, 24, 'During the asthma attack, she was ______ like a fish out of water.  ', ' gasping  ', ' gapping  ', ' grasping  ', ' grabbing				   ', '', '1');
INSERT INTO `data` VALUES (169, 24, 'The ______ asylum is both hospital and jail.  ', ' orphan  ', ' refuged  ', ' political  ', ' insane				   ', '', '4');
INSERT INTO `data` VALUES (170, 24, 'The ______ ruthlessly booed the lousy actor off the stage.  ', ' judge  ', ' hostess  ', ' audience  ', ' referee				   ', '', '3');
INSERT INTO `data` VALUES (171, 24, 'You should ______ your seatbelt when you drive or take a car.  ', ' fasten  ', ' purify  ', ' bleach  ', ' shovel				   ', '', '1');
INSERT INTO `data` VALUES (172, 24, 'If you live in an area where the air is polluted, it might be a good idea to purchase a machine that ______ the air in your home.  ', 'purifies  ', ' bleaches  ', ' extinguishes  ', ' reinforces', '', '1');
INSERT INTO `data` VALUES (173, 24, 'The gentleman drank the wine slowly, ______ every drop.  ', ' savoring  ', ' haunting  ', ' rejecting  ', ' minding				   ', '', '1');
INSERT INTO `data` VALUES (174, 24, 'MBA stands for Master of Business ______.  ', ' Application  ', ' Administration  ', ' Association  ', ' Assimilation				   ', '', '2');
INSERT INTO `data` VALUES (175, 24, 'On hearing the bell ring, the dull students ______ to life and rushed out of the classroom.  ', ' sprang  ', ' founded  ', ' dropped  ', ' winded				   ', '', '1');
INSERT INTO `data` VALUES (176, 24, 'After a long talk with his wife, Joe finally ______ the idea of moving to the big city.  ', ' stretched  ', ' concluded  ', ' embraced  ', ' challenged				   ', '', '3');
INSERT INTO `data` VALUES (177, 24, 'To keep the air clean in hospitals, air purifiers are placed in public areas to ______ the atmosphere.  ', 'purify  ', ' intensify  ', ' classify  ', ' falsify ', '', '3');
INSERT INTO `data` VALUES (178, 24, 'Because of its rich farmlands and abundant natural resources, America is sometimes referred to as a land of ______.  ', ' plenty  ', ' blossom  ', ' extension  ', ' pests			   ', '', '1');
INSERT INTO `data` VALUES (179, 24, 'Presidents of democratic countries must speak very ______ if they wish the citizens to follow their lead.  ', ' generally  ', ' persuasively  ', ' geographically  ', ' personally			   ', '', '2');
INSERT INTO `data` VALUES (180, 24, 'Jason dropped a small rock into the ______ and listened for it to hit the water below in order to see how deep the ______ really was.（兩格為同一個字。）  ', ' flock  ', ' mist  ', ' well  ', ' pile			   ', '', '3');
INSERT INTO `data` VALUES (181, 24, 'The anxious parents didn''t ______ hope of finding their missing son.  ', ' savor  ', ' perform  ', ' abandon  ', ' unfurl 				   ', '', '3');
INSERT INTO `data` VALUES (182, 24, 'Government officers ______ with many experts before passing the new law forbidding smoking in offices and restaurants.  ', 'exhibited  ', ' consulted  ', ' inhabited  ', ' challenged', '', '2');
INSERT INTO `data` VALUES (183, 24, 'He didn''t have time to read the entire book, so he just read the ______ published in the local newspaper.  ', ' excerpts  ', ' directory  ', ' textbook  ', ' anthology			   ', '', '1');
INSERT INTO `data` VALUES (184, 24, 'The summer program is designed to give the young athletes the chance to ______ their skills.  ', ' fantasize  ', ' surround  ', ' sharpen  ', ' promise				   ', '', '3');
INSERT INTO `data` VALUES (185, 24, 'The ______ prisoners were no longer dangerous as they had no way of escaping.  ', ' aboriginal  ', ' assertive  ', ' bound  ', ' prehistoric				   ', '', '3');
INSERT INTO `data` VALUES (186, 24, 'The well-known scientist was born with a severely ______ right foot, but he never lost his courage to follow his dream.  ', ' deformed  ', ' composed  ', ' promised  ', ' sharpened			   ', '', '1');
INSERT INTO `data` VALUES (187, 24, 'John''s murder trial showed that the justice system is ______ and needs further amendment.  ', 'fallible  ', ' reliable  ', ' eatable  ', ' liable', '', '1');
INSERT INTO `data` VALUES (188, 24, 'Betty scattered grain for her ______ of ducks to eat.  ', ' bundle  ', ' pile  ', ' pair  ', ' flock				   ', '', '4');
INSERT INTO `data` VALUES (189, 24, 'A ______ was said to pass through the haunted house when there was a full moon.  ', ' identity  ', ' version  ', ' sense  ', ' phantom 				   ', '', '4');
INSERT INTO `data` VALUES (190, 24, 'A(n) ______ is a deep valley between cliffs, with carved steep sides by a river.  ', ' planetarium  ', ' gorge  ', ' aboriginal  ', ' oracle				   ', '', '2');
INSERT INTO `data` VALUES (191, 24, 'Singers performing Mozart''s operas often dress in historical ______.  ', ' wrappings  ', ' warfares  ', ' costumes  ', ' consultants				   ', '', '3');
INSERT INTO `data` VALUES (192, 24, 'The chief executive officer ______ that there was no other way out of the crisis and therefore let others take over the enterprise.  ', 'conceived  ', ' received  ', ' deceived  ', ' perceived', '', '4');
INSERT INTO `data` VALUES (193, 24, 'To turn the desert into fertile and ______ land, many engineers have been working on building a canal.  ', ' productive  ', ' shadowy  ', ' mysterious  ', ' musical			   ', '', '1');
INSERT INTO `data` VALUES (194, 24, 'The hot summer ______ the grass and flowers.  ', ' drifted  ', ' extended  ', ' withered  ', ' forbade				   ', '', '3');
INSERT INTO `data` VALUES (195, 24, 'The early morning ______ means it will be sunny later on.  ', ' mist  ', ' flock  ', ' shadow  ', ' pest				   ', '', '1');
INSERT INTO `data` VALUES (196, 24, 'Damage to the forests from the wildfire was ______ and profound because the whole ecological environments and food chains are destroyed thoroughly.  ', ' defensive  ', ' offensive  ', ' extensive  ', ' intensive		   ', '', '3');
INSERT INTO `data` VALUES (197, 24, 'Because he was seated in the front row, he had to ______ his body around to see who was sitting behind him.  ', 'twist  ', ' unlock  ', ' replicate  ', ' donate', '', '1');
INSERT INTO `data` VALUES (198, 24, 'He ______ me to a push-up contest.  I managed to win even if I couldn''t feel my arms at the end.  ', ' challenged  ', ' asserted  ', ' unveiled  ', ' interpreted			   ', '', '1');
INSERT INTO `data` VALUES (199, 24, 'A ______ is one who studies living things.  ', ' naturalist  ', ' photographer  ', ' bachelor  ', ' chemist 				   ', '', '1');
INSERT INTO `data` VALUES (200, 24, 'To help traditional manufacturing industries upgrade, the Ministry of Economic Affairs (MOEA) will also help train skilled workers, including those responsible for quality control; push for QC ______ and product licensing.  ', ' vaporization  ', ' violation  ', ' variation  ', ' verification	   ', '', '4');
INSERT INTO `data` VALUES (201, 24, 'Monica ran out of sugar, so she used honey as a ______ to sweeten the dessert.  ', ' substitute  ', ' substance.  ', ' instrument  ', ' donation				   ', '', '1');
INSERT INTO `data` VALUES (202, 24, 'I could imagine how the mouse felt when the ______ seized it.  ', ' act  ', 'mound ', ' hawk  ', ' scholarship', '', '3');
INSERT INTO `data` VALUES (203, 24, 'In spite of the fact that Iraq had been liberated by the invasion of the U.S. troops, many Iraqi children are still homeless and ______ by the agony of losing their parents killed either in air raids or roadside bombs.  ', ' traumas  ', ' traumatic  ', ' traumatized  ', ' traumatically', '', '3');
INSERT INTO `data` VALUES (204, 24, 'I don''t have enough money; that''s the ______ reason why I haven''t bought a new computer.  ', ' sole  ', ' moral  ', ' ethical  ', ' lonely', '', '1');
INSERT INTO `data` VALUES (205, 24, 'If the situation gets worse, ______ your advisor.  ', ' interpret  ', ' unveil  ', ' consult  ', ' challenge', '', '3');
INSERT INTO `data` VALUES (206, 24, 'The theater managed to ______ its audiences by cutting ticket prices.  ', ' boost  ', ' wrap  ', ' consult  ', ' exhibit', '', '1');
INSERT INTO `data` VALUES (207, 24, 'If their demands were not met, the tourists would be killed.  ', 'exhibit  ', ' prohibition  ', ' captive  ', ' inhabitation', '', '3');
INSERT INTO `data` VALUES (208, 24, 'After the wedding ceremony, the bride lifted up her ______ to kiss her husband.  ', ' veil  ', ' mound  ', ' warfare  ', ' gorge				   ', '', '1');
INSERT INTO `data` VALUES (209, 24, 'The experienced teacher insisted that ______ is more effective than punishment in disciplining students.  ', ' population  ', ' persuasion  ', ' conclusion  ', ' production			   ', '', '2');
INSERT INTO `data` VALUES (210, 24, 'It is sad to see racial discrimination resulting in acts of _______.  ', ' pollination  ', ' disaster  ', ' violence  ', ' shadow				   ', '', '3');
INSERT INTO `data` VALUES (211, 24, 'John''s been ______ from driving for a year due to his drunk driving.  ', ' suffered  ', ' banned  ', ' protected  ', ' departed				   ', '', '2');
INSERT INTO `data` VALUES (212, 24, 'A good man won''t sell out his friends; it''s not ______.  ', 'legal  ', ' logical  ', ' affordable  ', ' ethical', '', '4');
INSERT INTO `data` VALUES (213, 24, 'We had ______ weather during our vacation in Bali, with rain almost every day.  ', ' dignified  ', ' horrible  ', ' repetitive  ', ' fatal				   ', '', '2');
INSERT INTO `data` VALUES (214, 24, 'I can''t ______ the two boys over there based on their looks.  They look so similar.  ', ' authorize  ', ' horrify  ', ' differentiate  ', ' promote 				   ', '', '3');
INSERT INTO `data` VALUES (215, 24, 'The members of the church ______ the glory of their god by singing a song.  ', ' assassinate  ', ' heighten  ', ' oppress  ', ' exalt				   ', '', '4');
INSERT INTO `data` VALUES (216, 24, 'There is ______ no reason for Jimmy to be late for school, as he lives next door.  ', ' incredibly  ', ' absolutely  ', ' leisurely  ', ' authoritatively 				   ', '', '2');
INSERT INTO `data` VALUES (217, 24, 'The ______ of some whites against black people in America led to the modern civil rights movement.  ', 'nonviolence  ', ' glory  ', ' prejudice  ', ' liberty', '', '3');
INSERT INTO `data` VALUES (218, 24, 'People from many different groups live in this city.  Each ______ group has its own culture and customs.  ', ' absolute  ', ' ethnic  ', ' dignitary  ', ' drastic ', '', '2');
INSERT INTO `data` VALUES (219, 24, 'In those days, the ______ to the island was long and dangerous, but now it is quicker and safer.  ', ' directory  ', ' voyage  ', ' property  ', ' handicap ', '', '2');
INSERT INTO `data` VALUES (220, 24, 'The son ______ one of his kidneys to his father, whose kidneys were seriously impaired because of diabetics.  ', ' submitted  ', ' endowed  ', ' presented  ', ' donated', '', '4');
INSERT INTO `data` VALUES (221, 24, 'What is the point of going to the gym if you eat so much food ______?  ', ' absolutely  ', ' awfully  ', ' approximately  ', ' afterwards ', '', '4');
INSERT INTO `data` VALUES (222, 24, 'The best and most effective treatment for her cancer would be a bone-marrow ______.', 'surgery  ', ' operation  ', ' transplant  ', ' chemotherapy', '', '3');
INSERT INTO `data` VALUES (223, 24, 'After the concert, Maggie finally ______ her favorite singer''s autograph.  ', ' obtained  ', ' requested  ', ' abolished  ', ' enquired  				   ', '', '1');
INSERT INTO `data` VALUES (224, 24, 'In China, women used to have a very low ______; they were considered inferior to men.  ', ' status  ', ' leisure  ', ' dignity  ', ' immigration				   ', '', '1');
INSERT INTO `data` VALUES (225, 24, 'Why do I have to pretend to like people I ______ dislike?  It''s really ridiculous!  ', ' phonetically  ', ' afterwards  ', ' heartily  ', ' tightly 				   ', '', '3');
INSERT INTO `data` VALUES (226, 24, 'In this amusement park are ______ the actual surroundings in which dinosaurs are thought to have lived.  ', ' replicated  ', ' replayed  ', ' replenished  ', ' replaced			   ', '', '1');
INSERT INTO `data` VALUES (227, 24, 'After hiking up the mountain quickly, we rested, and then hiked back down at a(n) ______ pace.  ', 'authoritatively  ', ' absolutely  ', ' incredibly  ', ' leisurely ', '', '4');
INSERT INTO `data` VALUES (228, 24, 'Some of Taiwan''s ______ have behaved awfully, even fighting in public or accepting bribes.  ', ' conveyors  ', ' legislators  ', ' imitators  ', ' guarantors				   ', '', '2');
INSERT INTO `data` VALUES (229, 24, 'Tom felt a ______ when he spotted his ex-girlfriend in the crowd.  ', ' quiver  ', ' signature  ', ' explosion  ', ' shot				   ', '', '1');
INSERT INTO `data` VALUES (230, 24, 'My mom says that I should ______ good taste in art and music art to be a well-rounded person.  ', ' attempt  ', ' cultivate  ', ' repeat  ', ' tend 				   ', '', '2');
INSERT INTO `data` VALUES (231, 24, 'Give everybody an equal chance, regardless of race, color, ______, or sex.  ', ' creed  ', ' liberty  ', ' flesh  ', ' governor				   ', '', '1');
INSERT INTO `data` VALUES (232, 24, 'To say that your English is broken is to do yourself a(n) ______.  ', 'content  ', ' creed  ', ' molehill  ', ' injustice', '', '4');
INSERT INTO `data` VALUES (233, 24, 'Jenny is too young to ______ the big responsibility of running her father''s company.  ', ' undertake  ', ' possess  ', ' confine  ', ' oppose				   ', '', '1');
INSERT INTO `data` VALUES (234, 24, '______ exams are necessary when testing students of foreign languages to find out how well they hear and speak the language.  ', ' Remorseful  ', ' Oral  ', ' Weary  ', ' Crippled			   ', '', '2');
INSERT INTO `data` VALUES (235, 24, 'The witch ______ the handsome prince into a frog.  ', ' transformed  ', ' eliminated  ', ' liberated  ', ' heightened				   ', '', '1');
INSERT INTO `data` VALUES (236, 24, 'The coffee shop was so pleasant that they ______ there awhile just to enjoy the atmosphere.  ', ' mourned  ', ' lingered  ', ' trod  ', ' ill-used				   ', '', '2');
INSERT INTO `data` VALUES (237, 24, 'The fall of the stock market ______ a time of great economic difficulty for the country.  ', 'foreshadowed  ', ' shunned  ', ' preserved  ', ' roved', '', '1');
INSERT INTO `data` VALUES (238, 24, 'The ______ of this practice seems kind of mechanical, but it can be helpful for your pronunciation.  ', ' heritage  ', ' status  ', ' repetition  ', ' programming			   ', '', '3');
INSERT INTO `data` VALUES (239, 24, 'There was a big ______ in front of the TV station to protest obscenity in its variety shows.  ', ' throne  ', ' signal  ', ' witness  ', ' gathering', '', '4');
INSERT INTO `data` VALUES (240, 24, 'She suffered from severe depression.  One harsh word would send her into the depths of ______.  ', ' prejudice  ', ' nonviolence  ', ' despair  ', ' race', '', '3');
INSERT INTO `data` VALUES (241, 24, '______ children need to be taken away from their parents and given to foster parents to raise.  ', ' Ill-used  ', ' Weary  ', ' Neglected  ', ' Drunken', '', '3');
INSERT INTO `data` VALUES (242, 24, 'Because he saw the man robbing the bank, Tony is now serving as a(n) ______ at the man''s trial.  ', 'conductor  ', ' officer  ', ' audience  ', ' witness', '', '4');
INSERT INTO `data` VALUES (243, 24, 'He lived in a ______ of about 200 residents, 10 miles to the east of the town.  ', ' crook  ', ' nullification  ', ' hamlet  ', ' pilgrim				   ', '', '3');
INSERT INTO `data` VALUES (244, 24, 'Mother often feeds the stray dogs at the riverside park out of ______.  ', ' sorrow  ', ' compassion  ', ' impression  ', ' communism				   ', '', '2');
INSERT INTO `data` VALUES (245, 24, 'Many popular Christmas ______ are sung during the Christmas season.  ', ' abodes  ', ' carols  ', ' stockings  ', ' misers 				   ', '', '2');
INSERT INTO `data` VALUES (246, 24, 'Her singing voice is sweet, but she needs help with her skills; she''s a diamond in the ______.  ', ' oasis  ', ' excerpt  ', ' rough  ', ' symphony				   ', '', '3');
INSERT INTO `data` VALUES (247, 24, 'To his ______, the old man lost his son in the apartment fire.  ', 'sorrow  ', ' amazement  ', ' compassion  ', ' pity', '', '1');
INSERT INTO `data` VALUES (248, 24, 'Articles in newspapers are written in ______ instead of poetry.  ', ' poverty  ', ' welfare  ', ' carol  ', ' prose				   ', '', '4');
INSERT INTO `data` VALUES (249, 24, 'Concerning climatology, I have only a nodding ______ with this subject.  ', ' relationship  ', ' acquaintance  ', ' knowledge  ', ' sensation				   ', '', '2');
INSERT INTO `data` VALUES (250, 24, 'Helen was so frightened by the horror movie that she thought she saw a ______ around every corner as she walked home in the dark.  ', ' producer  ', ' phantom  ', ' chief  ', ' composer			   ', '', '2');
INSERT INTO `data` VALUES (251, 24, 'Andrew Lloyd Webber, the world''s most popular theater composer, has produced several ______ that have run for more than a decade on Broadway.  ', ' stations  ', ' vehicles  ', ' airliners  ', ' musicals			   ', '', '4');
INSERT INTO `data` VALUES (252, 24, 'Being thrown stones at, several stray dogs were ______ under the benches of the park.  ', 'horrified  ', ' shuddering  ', ' amazed  ', ' sweating', '', '2');
INSERT INTO `data` VALUES (253, 24, 'Vicky is a ______ girl.  Once she makes up her mind, she seldom gives up.  ', ' neglected  ', ' weary  ', ' remorseful  ', ' resolute				   ', '', '4');
INSERT INTO `data` VALUES (254, 24, 'The landslide, caused by the earthquake and heavy rain, was a real ______ for the villagers.    ', ' nightmare  ', ' fantasy  ', ' wonder  ', ' blessing				   ', '', '1');
INSERT INTO `data` VALUES (255, 24, 'The man known as the Elephant Man was born with a body so ______ that he appeared more animal than human.  ', ' intoxicated  ', ' magnificent  ', ' deformed  ', ' enormous			   ', '', '3');
INSERT INTO `data` VALUES (256, 24, 'Every time I look down from the top of a skyscraper, I feel ______.  ', ' giddy  ', ' generous  ', ' crippled  ', ' persevering				   ', '', '1');
INSERT INTO `data` VALUES (257, 24, 'Unfortunately, the terrible car accident ______ him for life.', 'disappeared  ', ' foreshadowed  ', ' crippled  ', ' imagined  ', '', '3');
INSERT INTO `data` VALUES (275, 26, '下列何者不是RS232典型特性？  ', '為25針(或接腳)之D型接頭　', '接收端大於3伏特為邏輯“0”　', '傳送端介於5伏特與 15伏特之間為邏輯“0”　', '屬於並聯傳送裝置。', '', '4');
INSERT INTO `data` VALUES (274, 26, '下那一種磁碟機存取速度最快？  ', '硬碟機　', '軟碟機　', '光磁碟　', '虛擬磁碟機(RAMDRIVE)。', '', '4');
INSERT INTO `data` VALUES (273, 26, '為了改善硬碟的存取速度應該定期執行下列那一個程式？  ', '磁碟掃描程式　', '磁碟重組程式　', '磁碟格式化程式　', '磁碟切割程式。', '', '2');
INSERT INTO `data` VALUES (272, 26, '對於8086/8088CPU而言，若IP=0004H，CS=0100H，DS=0200H，則CPU所指到的指令位址是在記憶體中何處？  ', '01004H　', '02004H　', '0104H　', '0204H。', '', '1');
INSERT INTO `data` VALUES (271, 26, 'Intel公司之8255A為並行週邊介面晶片(PPI)，下列敘述何者有錯誤  ', '8255A只有兩條位址輸入線A0和A1　', '8255A有三個可規劃之工作模式　', '8255有四個埠可以連接到I/O裝置　', '8255A內部有一控制暫存器，可寫入控制字組以決定8255A的工作模式　', '以上皆非。', '3');
INSERT INTO `data` VALUES (270, 26, '下列那一個LSI週邊IC是可程式化中斷控制器  ', '8259A　', '8251A　', '8253A　', '8255A。', '', '1');
INSERT INTO `data` VALUES (269, 26, 'RS-232C介面邏輯狀態為“1”時的電壓值是  ', '5V　', '－3V～－25V　', ' 3～ 25V　', '0V。', '', '2');
INSERT INTO `data` VALUES (267, 26, 'RS-232介面是屬於  ', '串列傳輸　', '並列傳輸　', '類比信號傳輸　', '調變設備　', '解調變設備。', '1');
INSERT INTO `data` VALUES (268, 26, '序列式介面(SeriesInterface)中最常見的是RS-232C，試問同一時間每次傳輸多少位元？  ', '1　', '8　', '16　', '32。', '', '1');
INSERT INTO `data` VALUES (276, 26, '下列有關於微電腦輸入/輸出(I/O)規劃的敘述何者錯誤？  ', '6502CPU是採記憶映像I/O(MemoryMappedI/O)　', 'Z-80採隔離式I/O(IsolatedI/O)或I/OMappedI/O　', '隔離式I/O有專用的I/O指令　', '隔離式I/O將I/O當作記憶體一部份來使用　', '記憶映像I/O使用記憶體資料傳送指令來做為存取I/O裝置的指令。', '4');
INSERT INTO `data` VALUES (277, 26, '自動測試系統中，IEEE-488匯流排採用  ', '20接腳　', '24接腳　', '30接腳　', '36接腳。', '', '2');
INSERT INTO `data` VALUES (278, 26, '下列有關於電腦輸入/輸出(I/O)規劃的敘述，何者錯誤？  ', '隔離式的I/O(isolatedI/O或I/OmappedI/O)有專用I/O指令　', '隔離式的I/O，其I/O與記憶體使用位址空間完全分開　', '隔離式的I/O容易以指令區分存取I/O或記憶體　', '記憶體映像I/O(memorymappedI/O)，不佔用記憶體容量　', '記憶體映像I/O，存取I/O時，使用記憶體指令。', '4');
INSERT INTO `data` VALUES (279, 26, 'CPU存取I/O裝置之資料，若採用中斷方式，有何特點  ', '可不經CPU傳送資料　', 'CPU需經常詢問I/O裝置　', '不需外加硬體控制信號　', '可即時反應，且不需經常詢問I/O裝置，可節省CPU的時間　', 'CPU中斷動作，不需儲存返回位址、狀態暫存器等。', '4');
INSERT INTO `data` VALUES (280, 26, '下列敘述中那一項不屬於IEEE-488之匯流排？  ', '資料匯流排　', '位址匯流排　', '資料傳輸控制線　', '介面管理線　', '信號接地線。', '2');
INSERT INTO `data` VALUES (281, 26, '當輸入輸出埠與中央處理單元(CPU)做資料的傳遞時，以中斷訊號通知CPU，要求CPU暫停原來的工作而處理輸入輸出埠，處理完畢之後，再恢復原來工作，此種方式稱為  ', '程式I/O　', '中斷I/O　', '區段傳送(DMA)　', '串列傳送　', '', '2');
INSERT INTO `data` VALUES (282, 26, '有關計算機I/O位址敘述，下列何者錯誤？  ', '直接I/O位址之存取需要IN與OUT專用指令　', '記憶體映像式I/O位址之存取與記憶位址之存取使用相同的指令　', '記憶體映像式I/O位址佔記憶體位址的一個小部分空間　', '直接式I/O位址屬於記憶體位址的一部分。', '', '4');
INSERT INTO `data` VALUES (283, 26, 'MODEM係指  ', '調制器　', '解碼器　', '數位交換機　', '數據傳送機。', '', '4');
INSERT INTO `data` VALUES (284, 26, '下列何者為數據機(Modem)之功能？  ', '二進位數與十進位數互作轉換　', '數位與類比訊號互作轉換　', '同步與非同步互作轉換　', 'EBCDIC碼與ASCII碼互作轉換。', '', '2');
INSERT INTO `data` VALUES (285, 26, '有個數據傳輸機(Modem)，其鮑率(BaudRate)為1200bps，若連續傳送5秒，則共傳送了多少位元組(Byte)資料？  ', '1200　', '750　', '240　', '120。', '', '2');
INSERT INTO `data` VALUES (286, 26, 'IBMPC，使用那一顆IC做為中斷處理？  ', '8088　', '8749　', '8259　', '8239。', '', '1');
INSERT INTO `data` VALUES (287, 26, '下列何種I/O方式，所需之硬體電路最少？  ', 'PollingI/O　', 'InterruptI/O　', 'ChannelI/O　', 'DMA。', '', '1');
INSERT INTO `data` VALUES (288, 26, '若CPU以交握式存取I/O裝置的資料，下列敘述何者正確？  ', '交握式資料傳送可以使兩個不同速度的裝置取得協調，使傳送錯誤減至最低　', '交握式資料傳送只能使用於詢問模式，所以效率較低　', '交握式資料傳送只能使用於I/OMappedI/O的結構　', '在傳送資料期間CPU將喪失匯流排之控制權　', '不經由CPU傳送資料。', '1');
INSERT INTO `data` VALUES (289, 26, '下列何者是計算機的輸入單元也是輸出單元？  ', '列表機　', '繪圖機　', '磁帶機　', '滑鼠。', '', '3');
INSERT INTO `data` VALUES (290, 26, '下列何者不是輸入裝置  ', '磁碟機　', '鍵盤　', '光學閱讀機　', '列表機。', '', '4');
INSERT INTO `data` VALUES (291, 26, 'IEEE-488Bus的信號線共有  ', '4條　', '8條　', '16條　', '32條。', '', '3');
INSERT INTO `data` VALUES (292, 26, '序列式界面(SerialInterface)最常見的是RS-232C，它每個時脈傳輸  ', '1位元　', '8位元　', '16位元　', '32位元。', '', '1');
INSERT INTO `data` VALUES (293, 26, 'IEEE-488Bus的資料線有  ', '1條　', '2條　', '4條　', '8條　', '64條。', '4');
INSERT INTO `data` VALUES (294, 26, '對於輸入/輸出(I/O)介面的控制方式，資料的轉移不經過中央處理單元(CPU)，而在I/O埠與記憶體之間直接傳送，為下列何者？  ', '程式I/O　', '中斷I/O　', '直接記憶體存取(DMA)　', '輪詢(Polling)　', '菊鏈式I/O。', '3');
INSERT INTO `data` VALUES (295, 26, 'MODEM(調變解調器)與電腦間傳送資料是以何者為介面？  ', 'IEEE-488　', 'Centronics　', 'GPIB　', 'RS232C。', '', '4');
INSERT INTO `data` VALUES (296, 26, 'IBMPC電腦中，使用哪一顆IC負責中斷處理  ', '8255　', '8253　', '8237　', '8259。', '', '4');
INSERT INTO `data` VALUES (297, 26, 'DMA(DirectMemoryAccess)處理速度快，適合大量資料傳送，主要原因為何？  ', '不必使用位址線　', '不必經由CPU　', '使用較多之控制線　', '使用較多之資料線。', '', '2');
INSERT INTO `data` VALUES (298, 26, '外接式數據機(MODEM)和個人電腦(PC)間，主要是利用那種通訊介面協定？  ', 'IEEE-488　', 'IEEE-332　', 'RS-232C　', 'RS-306D。', '', '3');
INSERT INTO `data` VALUES (299, 26, '儲存於下列何者的程式與資料，可以不經過週邊介面而直接載入電腦的CPU？  ', '網路　', '主記憶體　', '硬碟　', '光碟。', '', '2');
INSERT INTO `data` VALUES (300, 26, '下列何項週邊設備與電腦主機的連接介面通常是使用串列埠(serialport)？  ', '滑鼠　', '光碟機　', '終端顯示器(monitor)　', '硬碟。', '', '1');
INSERT INTO `data` VALUES (301, 26, 'IBMPC/AT所使用的可程式中斷控制器的編號為  ', '8237　', '8253　', '8255　', '8259。', '', '4');
INSERT INTO `data` VALUES (302, 26, '微電腦系統中常使用輸入/輸出裝置(如8255)來連接週邊裝置或元件，此8255中的控制暫存器之功用為何？  ', '規劃8255之工作模式　', '暫時儲存所要傳送之資料　', '作為8255和之間的資料通道　', '儲存I/O位址。', '', '1');
INSERT INTO `data` VALUES (303, 26, '微電腦系統以RS-232C串列方式傳輸資料至週邊裝置，其串列傳輸格式為１位元啟始位元，8位元資料1位元同位元，2位元結束位元若以2400鮑率(Baud-rate)連續傳送100個位元組(Byte)之資料，假設每位元組間沒有延遲，所需之時間為  ', '0.5秒　', '2.4秒　', '100秒　', '2400秒。', '', '1');
INSERT INTO `data` VALUES (304, 26, '對CPU而言，下列何種資料的存取量最為快速  ', '暫存器　', '快取記憶體(cache)　', '光碟記憶體　', '主記憶體。', '', '1');
INSERT INTO `data` VALUES (305, 26, '採用41256的DRAM設計32位元的記憶體系統，請問此系統記憶體至少有  ', '256kbytes　', '1Mbytes　', '2Mbytes　', '4Mbytes。', '', '2');
INSERT INTO `data` VALUES (306, 26, '單顆有8條位址線與1條資料線的DRAM，其記憶體容量為何？  ', '32kByte　', '64kByte　', '64Byte　', '8kByte。', '', '4');
INSERT INTO `data` VALUES (307, 26, '當位址被送到記憶晶片的位址接腳開始，到資料出現在記憶體的資料接腳為止，所需時間稱為  ', '記憶週期時間　', '存取時間　', '時脈時間　', '迴轉時間。', '', '2');
INSERT INTO `data` VALUES (308, 26, '如果80286CPU的記憶體系統容量是4Mbytes，請問需用64k×4bit的RAM幾個？  ', '32　', '64　', '128　', '192。', '', '3');
INSERT INTO `data` VALUES (309, 26, '下列何種不能作為記憶體的解碼電路？  ', 'PROM　', 'PAL　', '正反器　', '比較器。', '', '3');
INSERT INTO `data` VALUES (310, 26, '設計容量為128kbyte的記憶體，採用32k×8bit記憶元件4個，組合成64kword×16bit之記憶電路，它的MAR(memoryaddressregister)應要有幾個bit？  ', '15bit　', '16bit　', '17bit　', '18bit。', '', '2');
INSERT INTO `data` VALUES (311, 26, '要設計4M×8位元的記憶體，需使用幾顆256k×1位元的記憶晶片  ', '16　', '64　', '128　', '256。', '', '3');
INSERT INTO `data` VALUES (312, 26, '假設某一微處理機的位址匯流排(addressbus)為20位元，資料匯流排(databus)為16位元，其記憶器位址空間之使用情形如下：除了保留64k位元組予I/O裝置及64k位元組予系統EPROM外，其餘的位址空間全部使用32k×8SRAM元件填滿請問共需要多少個此類型的SRAM元件：  ', '14個　', '28個　', '5個　', '32個。', '', '2');
INSERT INTO `data` VALUES (313, 26, '計算機之主記憶體(mainmemory)有65k，則記憶體位置暫存器(memoryaddressregister)至少有  ', '15位元(bits)　', '16位元(bits)　', '17位元(bits)　', '18位元(bits)。', '', '3');
INSERT INTO `data` VALUES (314, 26, '設計容量為128kbyte的記憶體，採用32k×8bit記憶元件4個，組合成64kword×16bit之記憶電路，它的MAR(memoryaddressregister)應要有幾個bit？  ', '15bit　', '16bit　', '17bit　', '18bit。', '', '2');
INSERT INTO `data` VALUES (315, 26, '一部8位元微電腦，其地址線有16條，本系統現有60k記憶體，目前只剩下F000至FFFF的範圍可以做擴展用若手上有4個1k的記憶體，則我們最多只要幾個2對4且具有致能(enable)的解碼器，就可以把此系統擴展至64k記憶體？  ', '1個　', '2個　', '3個　', '4個。', '', '1');
INSERT INTO `data` VALUES (316, 26, '下列那一CPU恰可界接128kbyte的記憶體，且有較好的存取能力？  ', '有16條位址線，8條資料線　', '有17條位址線，8條資料線　', '有18條位址線，8條資料線　', '有19條位址線，8條資料線。', '', '2');
INSERT INTO `data` VALUES (317, 26, '在微電腦系統中要作為隨機讀寫的記憶體，且又希望在電源消失後能保有其內容，應採用  ', 'SRAM　', 'EPROM　', 'DRAM　', 'EEPROM。', '', '4');
INSERT INTO `data` VALUES (318, 26, '下列何者不是DRAM優於DRAM的特點？  ', '密度高　', '容量大　', '需作更新(refresh)　', '價格低。', '', '3');
INSERT INTO `data` VALUES (319, 26, '如果80286CPU的記憶體系統容量是4Mbyte，請問需用64k×4bit的RAM幾個？  ', '32　', '64　', '128　', '192。', '', '3');
INSERT INTO `data` VALUES (320, 26, '下列何者不能作為記憶體的解碼電路？  ', 'DRAM　', 'PAL　', '正反器　', '比較器。', '', '3');
INSERT INTO `data` VALUES (321, 26, '計算機的主記憶體有3k位元組(bytes)，則記憶體位址暫存器(register)需多少位元(bits)即足夠？  ', '10　', '11　', '12　', '13。', '', '3');
INSERT INTO `data` VALUES (322, 26, '以下所列的記憶裝置，何者存取時間(accesstime)最短？  A)滑鼠　', '光碟機　', '終端顯示器(monitor)　', '硬碟。', '', '', '1');
INSERT INTO `data` VALUES (323, 26, 'IBMPC/AT所使用的可程式中斷控制器的編號為  ', '8237　', '8253　', '8255　', '8259。', '隱藏記憶體(cache)　', '2');
INSERT INTO `data` VALUES (324, 26, '某一16位元CPU具有16Mbytes的位址空間，使用256k×1bit的DRAM作為系統主記憶體，請問此系統最小記憶體容量為  ', '32k　', '256k　', '512k　', '1Mbytes。', '', '3');
INSERT INTO `data` VALUES (325, 26, 'MOVBX，AX表示  ', '暫存器BX，AX值均改變　', '暫存器AX值改變，BX值不變　', '暫存器BX值改變，AX值不變　', '暫存器BX，AX值均不改變。', '', '3');
INSERT INTO `data` VALUES (326, 26, '如果執行前AX暫存器內容為100H，則執行指令MOVAX，200H後，AX暫存器內容為  ', '100H　', '200H　', '300H　', '無法確定。', '', '2');
INSERT INTO `data` VALUES (327, 26, '下列那一種組合語言指令敘述為直接定址模式？  ', 'MOVAX，BX　', 'MOVAL，4BH　', 'MOVCL，[3FFFH]　', 'DAA。', '', '3');
INSERT INTO `data` VALUES (328, 26, '下列組合語言指令敘述何者為立即定址模式？  ', 'MOVAX，BX　', 'MOVAL，4BH　', 'MOVCL，[3FFFH]　', 'DAA。', '', '2');
INSERT INTO `data` VALUES (329, 26, '指令INCA是屬於下列那一種定址模式？  ', '立即定址　', '暫存器間接定址　', '基底定址　', '索引定址模式。', '', '2');
INSERT INTO `data` VALUES (330, 26, '在80X88指令中"MOVAX，[BX] 8"是何種定址模式？  ', '立即定址　', '基底定址　', '基接定址　', '直接索引定址。', '', '1');
INSERT INTO `data` VALUES (331, 26, '在8088暫存器間接定址模式中所使用的暫存器，下列那一個暫存器是錯誤的？  ', 'BX　', 'BP　', 'SP　', 'SI。', '', '3');
INSERT INTO `data` VALUES (332, 26, '若已知8088CPU的暫存器AX的內容為1234H，暫存器BX的內容為5678H，則執行指令MOVAX，BX後的暫存器AX，BX內容為何？  ', 'AX=1234H，BX=5678H　', 'AX=5678H，BX=1234H　', 'AX=5678H，BX=5678H　', 'AX=1234H，BX=1234H。', '', '3');
INSERT INTO `data` VALUES (333, 26, '有關組合語言及其格式之敘述，何者錯誤？  ', '組合語言之助記憶符(MemonicsSymbol)代表動作　', '助記憶符號後之運算元可有可無　', '組合語言經編譯程式(Compiler)翻譯成機器語言　', '註解欄的內容不會被翻成機器語言。', '', '3');
INSERT INTO `data` VALUES (334, 26, '在組合語言指令格式中，那一個欄位是不可省略？  ', '標記　', '運算碼　', '運算元　', '註解。', '', '2');
INSERT INTO `data` VALUES (335, 26, '在80X86指令中，指令MOVAX，[BX SI]為那一種定址模式？  ', '立即定址　', '基底定址　', '基底索引定址　', '暫存器定址。', '', '3');
INSERT INTO `data` VALUES (336, 26, '下列那種定址模式，執行速度最快？  ', '立即定址法　', '暫存器定址法　', '索引定址法　', '基底定址法。', '', '1');
INSERT INTO `data` VALUES (337, 26, '通常設定下列那一個旗標，可使一微處理機在執行完每一指令時，自動地產生內部中斷，使指令一個一個地執行，以便偵錯？  ', 'TF(Trap)陷阱　', 'ZF(Zero)零　', 'SF(Sing)符號　', 'OF(Overflow)溢位　', '(Carry)進位。', '1');
INSERT INTO `data` VALUES (338, 26, '對於8088/8086指令MOVAX,3而言，取得來源運算元"3"所使用之定址模式是下列何者？  ', '暫存器定址　', '直接定址　', '立即定址　', '暫存器間接定址　', '基底定址。', '3');
INSERT INTO `data` VALUES (339, 26, '對於8088/8086CPU而言，若IP=0004H，CS=0100H，DS=0200H，則CPU所指到的指令位址是在記憶體何處？  ', '0104H　', '01040H　', '0204H　', '02040H　', '01004H。', '5');
INSERT INTO `data` VALUES (340, 26, '微處理器中之指令暫存器是用來儲存何種資料？  ', '位址　', '指令之運算碼　', '狀態旗標　', '指令之運算元。', '', '2');
INSERT INTO `data` VALUES (341, 26, '在8086微處理器中，若使用AX暫存器時，其AX代表之功用為何？  ', '狀態旗標暫存器　', '8位元堆疊指標暫存器　', '16位元累加暫存器　', '16位元段暫存器。', '', '3');
INSERT INTO `data` VALUES (342, 26, '組合語言程式中常使用之虛擬指令(Pseudo-opcode)，其功用為何？  ', '作為運算用　', '沒有特定動作，只是作為執行時間之延遲　', '提供相關資料，命令組譯器作某些特定的工作　', '指引CPU之執行動作。', '', '3');
INSERT INTO `data` VALUES (343, 26, 'MOVAX(BX 55H)指令使用的是那種定址方式？  ', '直接定址　', '直接索引位址　', '基底相對定址　', '基底索引定址。', '', '3');
INSERT INTO `data` VALUES (344, 26, 'RAM2114為1K×4的記憶器，要組成64kB的主記憶體，需要  ', '16個2114RAM　', '32個2114RAM　', '48個2114RAM　', '64個2114RAM　', '128個2114RAM。', '5');
INSERT INTO `data` VALUES (345, 26, '單一正反器，可儲存多少個位元的資訊  ', '1位元　', '2位元　', '4位元　', '8位元　', '無法儲存。', '1');
INSERT INTO `data` VALUES (346, 26, '做微電腦實驗時常用到DRAM(DynamicRandomAccessMemory)，請將下列元件中，選出DRAM來  ', '8080或8086　', '6800或68000　', '41256　', '7400或7404。', '', '3');
INSERT INTO `data` VALUES (347, 26, '組合一個32KByte記憶體，採用何者元件來組合最適合  ', 'DRAM256K×1Bits　', 'DRAM64K×4Bits　', 'SRAM64K×4Bits　', 'SRAM16K×8Bits。', '', '4');
INSERT INTO `data` VALUES (348, 26, '一個微處理機具有18條位址線，16條資料線，最多可直接接多少記憶體？  ', '64KByte　', '128KByte　', '256KByte　', '512KByte。', '', '3');
INSERT INTO `data` VALUES (349, 26, '在儲存位置內輸入資料  ', '會導致該位址編號的改變　', '會與該位址原先的內容相加　', '會破壞該位址原先的內容　', '稱為讀出動作。', '', '3');
INSERT INTO `data` VALUES (350, 26, '用來將資料編碼的8位元的單位稱為  ', '字組　', '資料集　', '位元組　', 'K。', '', '3');
INSERT INTO `data` VALUES (351, 26, '某計算機之“位址匯流排”(addressbus)有16條線，則其儲存位置多可達  ', '32KBYTES　', '64KBYTES　', '128KBYTES　', '256KBYTES。', '', '2');
INSERT INTO `data` VALUES (352, 26, '微電腦實驗時常用到DRAM(DynamicRandomAccessMemory)，請就下列元件中，選出DRAM來  ', '8080或8086　', '6800或68000　', '27256　', '7400或7404　', '以上皆非。', '5');
INSERT INTO `data` VALUES (353, 26, '某計算機之記憶容量為64K，即表示可儲存的位元組為  ', '64　', '1024　', '6400　', '65536。', '', '4');
INSERT INTO `data` VALUES (354, 26, '一個4位元(Bit)為一字語(Word)的2048位元記憶器，需要多少條位址線？  ', '6條　', '7條　', '8條　', '9條　', '10條。', '4');
INSERT INTO `data` VALUES (355, 26, '關於隨機存取記憶體RAM，下列敘述何者錯誤？  ', '靜態(static)RAM是利用正反器記憶　', '靜態RAM必須每隔一段時間要刷新(refresh)否則記憶會消失　', '動態(Dynamic)RAM是利用電容器作記憶　', '動態RAM為MOSFET結構　', '兩種RAM在電源開關(off)後資料自行消失。', '2');
INSERT INTO `data` VALUES (356, 26, '微電腦主機板上常見使用動態記憶體(DRAM)來取代早期曾被廣泛使用的靜態隨機存取記憶體(SRAM)，其設計上的理由如下述，何者不為真？  ', '可提高單位容積內的記憶密度　', '功率損耗較小　', '成本較低，較經濟　', '較不受停電影響。', '', '4');
INSERT INTO `data` VALUES (357, 26, '編號4164的動態記憶體有多種不同型式，下列何者速度最快？  ', '4164-6　', '4164-8　', '4164-10　', '4164-12。', '', '1');
INSERT INTO `data` VALUES (358, 26, '某一記憶體共有12個位址線，則此記憶體共有多少個位址？  ', '1024　', '2048　', '4096　', '5120。', '', '3');
INSERT INTO `data` VALUES (359, 26, '半導體記憶體之ROM及RAM之主要區別是  ', '前者以磁片記錄，後者為磁帶　', '前者可隨意讀寫，後者僅能讀　', '前者只能讀，後者可隨意讀寫　', '前者為主記憶體，後者為輔助記憶體。', '', '3');
INSERT INTO `data` VALUES (360, 26, '編號2732的EPROM具有資料進出線O0～O7，位址選擇線A0～A11，其總儲存位元(bit)數目為  ', '212個　', '213個　', '214個　', '215個　', '216個。', '4');
INSERT INTO `data` VALUES (361, 26, '當資料一旦存入後，非經特別的處理，不能改變其內容，所儲存的資料只能讀取，但無法將新資料寫入的記憶體，稱為  ', 'RAM　', 'CPU　', 'CAD　', 'ROM　', '以上皆非。', '4');
INSERT INTO `data` VALUES (362, 26, '記憶器DRAM中之D代表  ', 'Digital　', 'Data　', 'Dynamic　', 'Drive。', '', '3');
INSERT INTO `data` VALUES (363, 26, '可消除及可規劃唯讀記憶體的縮寫為  ', 'PROM　', 'ROM　', 'RAM　', 'EPROM。', '', '4');
INSERT INTO `data` VALUES (364, 26, '下列那一種記憶體(Memory)元件，可以不用紫外線清除，但仍可以執行寫入(Write)和讀取(Read)  ', 'ROM　', 'PROM　', 'EPROM　', 'EEPROM。', '', '4');
INSERT INTO `data` VALUES (365, 26, '某一唯讀記憶體共有10條位址線，則此記憶體共有  ', '1024個記憶位址　', '2048個記憶位址　', '4096個記憶位址　', '8192個記憶位址。', '', '1');
INSERT INTO `data` VALUES (366, 26, '編號6264為8K×8之記憶體IC，若要組成256K×16之記憶體系統，則須幾顆6264？  ', '32　', '64　', '96　', '128。', '', '2');
INSERT INTO `data` VALUES (367, 23, '在專案規劃初期，分析競爭對手的主要目的為何?', '幫助設計團隊與客戶在同類商品中找出自己得定位', '測試客戶的商品在市場上的接受度', '確認網站的媒體類型', '制定可用性測試計畫', '', '1');
INSERT INTO `data` VALUES (368, 23, '在預設情況下，Flash無法在.SWF檔中呈現尚未輸入到「動態欄位」裡的文字，請問底下哪個方是可以解決這個問題?', '將欄位類型改成「輸入文字」類型', '選用OpenType字體', '將「消除鋸齒選項」改成「使用裝置字體」', '設定多欄文字', '', '3');
INSERT INTO `data` VALUES (369, 23, '底下哪一種方法不可測視網站的可用性?', '邀請朋友瀏覽網站並回饋意見', '錄影記下用戶的操作過程', '運用軟體記錄使用者的操作情形', '透過觀察原紀錄使用者的操作情況', '', '1');
INSERT INTO `data` VALUES (370, 23, '下列哪一種情況不一定需要使用TLF文字引擎?', '建立多欄文字', '套用3D旋轉效果', '套用濾鏡', '轉換成小型大寫字', '', '3');
INSERT INTO `data` VALUES (371, 23, '以下關於網站導覽功能的描述，何者有誤?', '不應該僅使用文字，要附帶使用圖像和符號標誌', '整個網站應該採用一致的導覽列設計', '把相關的連結選項組織在一起', '要降低參訪者連結到目標網頁所需的點選次數', '', '1');
INSERT INTO `data` VALUES (372, 23, '以下何者是正確的智慧財產權的概念?', '使用P2P分享商業軟體，只要不涉及販售營利，就沒有違法', '自己花錢買的雜誌，掃瞄其中幾頁用e-mail發給親朋好友，沒有違法', '從電視轉錄的電影，可以放到網站上播放', '著作權是有期限的權利，在一定期限經過後，即屬於公共領域(public domain)，任何人皆可自由利用', '', '4');
INSERT INTO `data` VALUES (373, 23, '在專案初期研究目標用戶主要的目的是什麼?', '了解團隊需求', '了解用戶參觀的動機', '了解網站的定位', '分析競爭對手的優缺點', '', '2');
INSERT INTO `data` VALUES (374, 23, '確立網站的目標群眾時，下列哪一項不是考量的因素?', '參訪者前來觀看網站的原因和需求', '參訪者的年齡層與性別', '參訪者採用的瀏覽器版本', '參訪者的經濟狀況與收入', '', '3');
INSERT INTO `data` VALUES (375, 23, '色相是哪個字的同義詞?', '顏色', '色彩的鮮豔程度', '色彩的深淺變化', '以上皆非', '', '1');
INSERT INTO `data` VALUES (376, 23, '在設計過程中使用網格的主因是?', '物件不會貼其網格，所以更容易調整他們的位置', '測量物件的尺寸', '有助於充分運用舞台的空間', '幫助我們調配版面的空間', '', '4');
INSERT INTO `data` VALUES (377, 23, '製作Flash影片時，舞台的尺寸大小取決於：', '目標群眾的作業速度', '目標群眾的連線速度', '目標群眾的螢幕解析度', '軟體公司', '', '3');
INSERT INTO `data` VALUES (378, 23, '下列哪些是良好Flash設計的因素', '運用多種色彩營造出鮮明的印象並吸引用戶的目光', '大量採用動畫', '審慎使用音效', '盡可能提供多種導覽樣式', '', '3');
INSERT INTO `data` VALUES (379, 23, '底下哪一個敘述是正確的?', '點陣影像無法被動態載入', '修改外部內容時，就要重新繪出.swf影片', '使用動態內容，可降低初始下載時間', 'Flash可以不受限制地載入任何網域的動態內容', '', '3');
INSERT INTO `data` VALUES (380, 23, 'ActionScript3.0中，建立連線請求的類別物件式：', 'URLRequest', 'Request', 'getURL', 'URLLoader', '', '1');
INSERT INTO `data` VALUES (381, 23, '若想要在不變更動畫內容的情況下，延長播放時間，最佳做法為何?', '插入關鍵影格', '插入空白關鍵影格', '插入影格', '增加影格速率', '降低影格速率', '5');
INSERT INTO `data` VALUES (382, 23, '底下何者不是「險事物件容器(DisplayObjectContainer)」?', 'Stage', 'MovieClip', 'SimpleButton', 'Loader', '', '3');
INSERT INTO `data` VALUES (383, 23, '連結網頁時，若需要一併從ActionScript3.0傳送資料到伺服器，需要運用到哪個類別物件?', 'VARLoader', 'URLLoader', 'LoadVariables', 'URLVariables', '', '4');
INSERT INTO `data` VALUES (384, 23, '下列哪個組件用於播放Flash視訊影片?', 'FLAPlayback', 'ComboBox', 'Label', 'DataGrid', '', '1');
INSERT INTO `data` VALUES (385, 23, '在專案的設計過程，進行可用性測試的主要目的為何?', '將抽像內容具體化', '評估網頁的版型設計是否合宜', '評估網站的商業目標', '評估網站特定的介面是否意於使用', '', '4');
INSERT INTO `data` VALUES (386, 23, '底下哪一屬性可透過「發布設定」面板調整?', '舞台尺寸', '關鍵影格', 'Flash player版本', '預設字體', '', '3');
INSERT INTO `data` VALUES (387, 23, '下列哪一向不是自由變形工具的功用?', '縮放與旋轉圖像', '改變圖像的中心位置', '斜切圖像', '裁切圖像', '', '4');
INSERT INTO `data` VALUES (388, 23, 'Flash的「選色器」(Color Picker)面板包含幾種顏色?', '216色', '256色', '數千色', '1677萬色', '', '1');
INSERT INTO `data` VALUES (389, 23, '哪一個面板可以儲存程式碼並方便重複使用', '動作面板行為', '時間軸面板', '行為指令面版', '程式碼片段', '', '4');
INSERT INTO `data` VALUES (390, 23, '請問關於線框圖下列何者可以和其配對?', '展現網站的整體架構', '傳達視覺效果', '詳述人機介面或程式邏輯的細節', '展示頁面的功能與結構', '', '4');
INSERT INTO `data` VALUES (391, 23, '請問關於流程圖下列何者可以和其配對?', '展現網站的整體架構', '傳達視覺效果', '詳述人機介面或程式邏輯的細節', '展示頁面的功能與結構', '', '3');
INSERT INTO `data` VALUES (392, 23, '請問關於網站地圖下列何者可以和其配對?', '展現網站的整體架構', '傳達視覺效果', '詳述人機介面或程式邏輯的細節', '展示頁面的功能與結構', '', '1');
INSERT INTO `data` VALUES (393, 23, '請問關於螢幕設計圖下列何者可以和其配對?', '展現網站的整體架構', '傳達視覺效果', '詳述人機介面或程式邏輯的細節', '展示頁面的功能與結構', '', '2');
INSERT INTO `data` VALUES (394, 23, '下列哪個敘述用在ActionScript3.0中，將a_mc設定50%的透明度?', 'a_mc._alppha = 50;', 'a_mc.alpha = .5;', 'a_mc.alpha *= 5;', 'a_mc._alppha = 0.5;', '', '2');
INSERT INTO `data` VALUES (395, 23, '關於「影導圖層」，下列何者正確?', '關於建立補間動畫', '不會被匯出', '會增加影片檔的大小', '用於設定時間軸', '', '2');
INSERT INTO `data` VALUES (396, 23, '關於「影導圖層」，下列何者正確?', '關於建立補間動畫', '會被匯出', '會增加影片檔的大小', '用於輔助安排圖像位置', '', '4');
INSERT INTO `data` VALUES (397, 23, '在不縮減影格長度的情況下，若要讓某個圖層圖像想在顯示一段時間之後消失，你要運用?', '新增影格', '新增關鍵影格', '新增空白關鍵影格', '新增場景', '', '3');
INSERT INTO `data` VALUES (398, 23, 'ActionScript3.0程式碼可以放在哪一個地方?', '空白關鍵影格', '按鈕裡的時間軸', '按鈕物件本身', '元件', '', '1');
INSERT INTO `data` VALUES (399, 23, 'ActionScript3.0程式碼可以放在哪一個地方?', '元件', '按鈕裡的時間軸', '按鈕物件本身', '.as文件', '', '4');
INSERT INTO `data` VALUES (400, 23, '文件欄位的哪一個屬性可以動態設定其文字內容?', 'txt', 'text', 'var', 'int', '', '2');
INSERT INTO `data` VALUES (401, 23, '文件欄位的哪一個屬性可以動態設定其文字內容?', 'txt', 'radio', 'var', 'htmlText', '', '4');
INSERT INTO `data` VALUES (402, 23, '使用裝置字體的缺點：', '縮減檔案大小', '裝置字體不會有鋸齒外觀', '可能無法在用戶端呈現指定的字體', '裝置字體將嵌入swf檔', '', '3');
INSERT INTO `data` VALUES (403, 23, '下列哪一個檔案類型不式視訊檔?', 'WMV', 'M4V', 'WAV', '3GP', '', '3');
INSERT INTO `data` VALUES (404, 27, '計劃展示一批用戶端電腦，電腦上沒有儲存裝置。這些電腦會透過伺服器開機，並載入所有的檔案與應用程式包括作業系統。此時應該使用下列何種運算模型？  ', '伺服器型 ( 2)集中式  ', '合作式  ', '分散式。', '', '', '2');
INSERT INTO `data` VALUES (405, 27, '目前有12台電腦在網路上，預計再添置5台。網路安全非考慮重點，重要的是他們必須定期備份下所有的資料。此時採取何種網路最好？ ', '伺服器型   ', '對等   ', '區域網路   ', '都會網路。', '', '1');
INSERT INTO `data` VALUES (406, 27, '下列何者是對等網路的優點？  ', '易於備份  ', '資料分散在整個網路上  ', '易於設定  ', '使用了功能強大的伺服器。', '', '3');
INSERT INTO `data` VALUES (407, 27, '下列何種是伺服器型網路所提供的特性？  ', '容錯能力  ', '安全性  ', '小型用戶端  ', '以上皆是', '', '4');
INSERT INTO `data` VALUES (408, 27, '何種網路服務允許使用者維護網路上的資訊？  ', '檔案服務   ', '訊息服務   ', '目錄服務   ', '資料庫服務。  ', '', '3');
INSERT INTO `data` VALUES (409, 27, '校園內有網路分布在數個建築物內，一些建築物位於郊區，環繞著教育中心，此時展現出何種網路類型？  ', 'LAN   ', 'MAN   ', 'WAN   ', 'TAN', '', '2');
INSERT INTO `data` VALUES (410, 27, '下列何者是檔案服務的成員？  ', '檔案保存  ', '印表佇列管理  ', '電子郵件  ', '物件管理。', '', '1');
INSERT INTO `data` VALUES (411, 27, '下列何者是訊息服務的功能？ ', '電子郵件 ', '群組軟體 ', '傳送視訊 ', '以上皆是。', '', '4');
INSERT INTO `data` VALUES (412, 27, '下列何者不是合作式運算的特徵？ ', '存取快速 ', '允許各式各樣的桌上型電腦設定與功能  ', '使用到了整個網路上的運算能力  ', '提供高度的安全性。', '', '4');
INSERT INTO `data` VALUES (413, 27, '新添之伺服器負責處理由用戶端傳過來的需求，然後再將處理好的資料送回用戶端，這種伺服器屬於  ', '檔案伺服器  ', '列印伺服器  ', '應用伺服器  ', '通訊伺服器。', '', '3');
INSERT INTO `data` VALUES (414, 27, '在傳輸前後資料透過何種方法進行錯誤控制？  ', '停止與等待  ', '循環餘數檢查  ', '區段重新排序  ', '流量控制。', '', '2');
INSERT INTO `data` VALUES (415, 27, '透過鏈結層傳輸過去的資料，目的端裝置會傳回確認訊號，為何種連線？  ', '半雙工  ', '區段重新排序  ', '免接式  ', '接通式。', '', '4');
INSERT INTO `data` VALUES (416, 27, '系統會以主控裝置檢查網路上的次級裝置，看這些裝置是否需要傳輸資料，此即為：   ', '輪詢   ', '記號傳遞   ', 'CSMA/CD   ', 'CSMA/CA。', '', '1');
INSERT INTO `data` VALUES (417, 27, '在兩個通訊裝置之間建立專屬連線的交換傳輸方式是：   ', '訊息交換   ', '虛擬線路   ', '線路交換   ', '封包交換。', '', '3');
INSERT INTO `data` VALUES (418, 27, '允許雙向同時對話的連線是：   ', '半雙工   ', '全雙工   ', '單工   ', '資料元。', '', '2');
INSERT INTO `data` VALUES (419, 27, '允許電腦互相通訊的語言是：  ', '協定  ', '定址  ', '輪詢  ', '對話。', '', '1');
INSERT INTO `data` VALUES (420, 27, '何種網路系統在大型網路上運行得最佳？   ', '搶線型   ', '仲裁型   ', '單工   ', '半雙工', '', '2');
INSERT INTO `data` VALUES (421, 27, '那個OSI運作層會將資料打包成訊框？   ', '傳輸層   ', '實體層   ', '會議層   ', '鏈結層。', '', '4');
INSERT INTO `data` VALUES (422, 27, '那個OSI運作層負責將資料透過網路路由傳輸出去？   ', '實體層   ', '網路層   ', '會議層   ', '應用層。', '', '2');
INSERT INTO `data` VALUES (423, 27, '那個OSI運作層以檢查碼實作錯誤檢查機制？  ', '邏輯連結控制層  ', '媒體存取控制層  ', '應用層  ', '會議層。', '', '1');
INSERT INTO `data` VALUES (424, 27, 'Microsoft Window NT作業系統使用何種網路卡驅動程式？  ', 'ODI  ', 'NDIS  ', 'MAC  ', '網路卡驅動程式。', '', '2');
INSERT INTO `data` VALUES (425, 27, 'MAC匯流排是IBM發展用來克服何種匯流排的限制？  ', 'EISA  ', 'PCI  ', 'ISA  ', 'VESA。', '', '3');
INSERT INTO `data` VALUES (426, 27, '下列何者用介面卡即可直接存取電腦記憶體？  ', 'IRQ  ', 'I/O  ', '共享記憶體位址  ', 'DMA。', '', '4');
INSERT INTO `data` VALUES (427, 27, '何種網路卡使用UTP傳輸線？  ', 'BNC  ', 'RJ-45  ', 'AUI  ', 'DIX。', '', '2');
INSERT INTO `data` VALUES (428, 27, '電子訊號較不受下列何種問題的影響？  ', '串音  ', '雜訊  ', '衰減  ', '反射。', '', '4');
INSERT INTO `data` VALUES (429, 27, '大多數家庭有線電視系統都採用何種傳輸線？  ', '同軸電纜線  ', 'UTP  ', 'STP   ', '光纖。', '', '1');
INSERT INTO `data` VALUES (430, 27, '下列何者為無線式網路媒體？  ', '光纖  ', '同軸電纜線  ', '無遮蔽式雙絞線  ', '紅外線。', '', '4');
INSERT INTO `data` VALUES (431, 27, '記號環網路使用何種編碼法？  ', '回歸為零  ', '單極  ', '差動式曼徹斯特  ', '曼徹斯特。', '', '3');
INSERT INTO `data` VALUES (432, 27, '類比訊號不使用何種編碼法？  ', '振幅偏移鍵制  ', '頻率偏移鍵制  ', '相位偏移鍵制  ', '單極。', '', '4');
INSERT INTO `data` VALUES (433, 27, '表示同軸電纜線規格的單位為何？  ', '直徑  ', '歐姆  ', '阻抗  ', '電磁干擾。', '', '1');
INSERT INTO `data` VALUES (434, 27, '乙太網路是用那種媒體存取方式？   ', 'CSMA/CD   ', 'CSMA/CA   ', '記號傳遞   ', '輪詢。', '', '1');
INSERT INTO `data` VALUES (435, 27, '記號網路是用那種媒體存取方式？   ', 'CSMA/CD   ', 'CSMA/CA   ', '記號傳遞   ', '輪詢。', '', '3');
INSERT INTO `data` VALUES (436, 27, '是用那種媒體存取方式？   ', 'CSMA/CD   ', 'CSMA/CA   ', '記號傳遞   ', '輪詢。', '', '3');
INSERT INTO `data` VALUES (437, 27, '那種實體拓樸需用到終端電阻？   ', '匯流排   ', '星狀   ', '環狀   ', '網狀。', '', '1');
INSERT INTO `data` VALUES (438, 27, '那種實體拓樸會讓每一對狀置都有個別直接的連線？   ', '匯流排   ', '星狀   ', '環狀   ', '網狀。', '', '4');
INSERT INTO `data` VALUES (439, 27, '那種實體拓樸是將工作站連到中央的狀置？   ', '匯流排   ', '星狀   ', '環狀   ', '網狀？  ', '', '2');
INSERT INTO `data` VALUES (440, 27, '那種實體拓樸只容許資料向一個方向傳輸？   ', '匯流排   ', '星狀   ', '環狀   ', '網狀。  ', '', '3');
INSERT INTO `data` VALUES (441, 27, 'NetWare 3.12網路是用那種訊框？  ', 'Ethernet_802.3   ', 'Ethernet_802.2   ', 'Ethernet_Ⅱ   ', 'IEEE。', '', '2');
INSERT INTO `data` VALUES (442, 27, '那種乙太網路標準是以10Mbps在UTP線上傳輸，並使用集線器？   ', '10Base-5   ', '10Base-2   ', '10Base-T   ', '10Base-FL。', '', '3');
INSERT INTO `data` VALUES (443, 27, 'ARCNET網路的速度為何？   ', '1.2.5Mbps   ', '4Mbps   ', '10Mbps   ', '16Mbps。', '', '1');
INSERT INTO `data` VALUES (444, 27, 'VG-AnyLAN是用那種媒體存取方式？   ', 'CSMA/CD   ', 'CSMA-CA   ', '記號傳遞   ', '需求優先。', '', '4');
INSERT INTO `data` VALUES (445, 27, '記號環MAU是用那種接頭？   ', 'BNC   ', 'RJ-45   ', '9-pin AUI   ', '一體成型。', '', '4');
INSERT INTO `data` VALUES (446, 27, 'ARCNET網路上最多可有多少節點？   ', '90   ', '100   ', '255   ', '300。', '', '3');
INSERT INTO `data` VALUES (447, 27, '記號環網路是由那個標準定義的？   ', 'IEEE 802.2   ', 'IEEE 802.3   ', 'IEEE-802.5   ', 'ATA。', '', '3');
INSERT INTO `data` VALUES (448, 27, '那種網路會使用兩個反向傳送的環路？   ', 'ARCNET   ', '以太網路   ', '記號環網路   ', 'FDDI。', '', '4');
INSERT INTO `data` VALUES (449, 27, '以下何者是IP位址？   ', '9.67.43.8   ', 'http://www.idgbooks.com   ', '00-C0-6D-10-47-8D   ', '0384CD:2766801。', '', '1');
INSERT INTO `data` VALUES (450, 27, 'Ping這個程式是使用那個協定？   ', 'TCP   ', 'IP   ', 'IDP   ', 'ICMP。', '', '4');
INSERT INTO `data` VALUES (451, 27, '下列那個協定是負責將IP址轉換為MAC位址？   ', 'TCP   ', 'ARP   ', 'UDP   ', 'DNS。', '', '2');
INSERT INTO `data` VALUES (452, 27, 'PX是在OSI的那一層上運作的？  ', '實體層   ', '鏈結層   ', '網路層   ', '傳輸層。', '', '3');
INSERT INTO `data` VALUES (453, 27, '那個IPX/SPX協定負責宣傳有網路資源可用？   ', 'RIP   ', 'SAP   ', 'NCP   ', 'SPX。', '', '2');
INSERT INTO `data` VALUES (454, 27, '下列何者是專屬的協定？   ', 'LocalTalk   ', 'EtherTalk   ', 'TokenTalk   ', 'NetBEUI。', '', '1');
INSERT INTO `data` VALUES (455, 27, '那個協定是用來與Hewlett-Packard 網路印表機通訊的？   ', 'DNA   ', 'DLC   ', 'IPX   ', 'IP。', '', '2');
INSERT INTO `data` VALUES (456, 27, '那個協定提供遠端存取的動態定址功能？   ', 'SLIP   ', 'PPP   ', 'ISDN   ', 'ATM。', '', '2');
INSERT INTO `data` VALUES (457, 27, '用在Internet上的主要協定組合為何？   ', 'TCP/IP   ', 'IPX/SPX   ', 'NetBEUI   ', 'DNA。', '', '1');
INSERT INTO `data` VALUES (458, 27, '那個協定是用來將電子郵件送到Internet上的伺服器？   ', 'UDP   ', 'FTP   ', 'POP   ', 'SMTP。', '', '2');
INSERT INTO `data` VALUES (459, 27, '中繼器是在OSI模型中的那層運作？   ', '實體層   ', '鏈結層   ', '網路層   ', '傳輸層。', '', '1');
INSERT INTO `data` VALUES (460, 27, '那種橋接器是用在記號環網路中？   ', '通透式   ', '來源-路由式   ', '轉譯式   ', '擴展樹。', '', '2');
INSERT INTO `data` VALUES (461, 27, '在以太網路中以電腦的MAC位址來過濾交通的多埠橋接器叫做？   ', '交換器   ', '通透橋接器   ', '轉譯橋接器   ', '來源-路由橋接器。', '', '1');
INSERT INTO `data` VALUES (462, 27, '路由器是在OSI模型中的那層運作？   ', '實體層   ', '鏈結層   ', '網路層   ', '傳輸層。', '', '3');
INSERT INTO `data` VALUES (463, 27, '那種裝置是用來連接T1和ISDN線路？   ', '數據機   ', 'CSU/DSU   ', '閘道器   ', '路由器。', '', '2');
INSERT INTO `data` VALUES (464, 27, '會傳送NetBEUI交通的路由器可稱之為？  ', '橋接器  ', '多工器  ', '路由橋接器  ', '閘道器。', '', '3');
INSERT INTO `data` VALUES (465, 27, '通透橋接器使用那種位址來過濾資料？  ', 'MAC位址  ', '網路位址  ', '電腦名稱  ', '工作群組名稱。', '', '1');
INSERT INTO `data` VALUES (466, 27, '下列那個ITU數據機協定定義 28.8Kbps的通訊速度？  ', 'V.14  ', 'V.42bis  ', 'V.32bis  ', 'V.34。', '', '4');
INSERT INTO `data` VALUES (467, 27, '那個裝置可用來將同一纜線上多個信號分離出來？  ', '數據機  ', 'CSU/DSU  ', '多工器  ', '路由器。', '', '3');
INSERT INTO `data` VALUES (468, 27, '那種裝置可在OSI模型的全部七層上運作？  ', '路由器  ', '集線器  ', '橋接器  ', '閘道器。', '', '4');
INSERT INTO `data` VALUES (469, 27, '下列何者並非工作群組的特性？  ', '對等式網路  ', '無集中式管理  ', '用來管理資源  ', '需使用PDC。', '', '4');
INSERT INTO `data` VALUES (470, 27, '下列那個字元不可用在使用者名稱中？  ', '', '@  ', '#  ', '* 。', '', '4');
INSERT INTO `data` VALUES (471, 27, '在工作群組中的什麼電腦一定得用共用級存取控制？  ', 'Windows NT伺服器  ', 'Windows NT工作站  ', 'Windows95/98  ', 'NetWare伺服器。', '', '3');
INSERT INTO `data` VALUES (472, 27, '那一項可用使用者設定檔來設定？  ', '使用者名稱  ', '密碼長度  ', '連線網路資源  ', '桌面設定。', '', '4');
INSERT INTO `data` VALUES (473, 27, '下面那種限制是不能用在Windows NT之中？  ', '最短密碼長度  ', '最長密碼長度  ', '密碼有效期間  ', '密碼唯一性。', '', '2');
INSERT INTO `data` VALUES (474, 27, '下列那種備份方式可用來備份所選檔案中有更改過的檔案且不會設定「保存」屬性？  ', '完全備份  ', '漸增式備份  ', '異動式備份  ', '複製。', '', '3');
INSERT INTO `data` VALUES (475, 27, '下列那種備份方式可用來備份所有選擇的檔案且不會設定「保存」屬性？  ', '完全備份  ', '漸增式備份  ', '異動式備份  ', '複製', '', '4');
INSERT INTO `data` VALUES (476, 27, '下列那種備份方式可用來備份所選檔案中有更改過的檔案且會設定「保存」屬性？  ', '完全備份  ', '漸增式備份  ', '異動式備份  ', '複製。', '', '2');
INSERT INTO `data` VALUES (477, 27, '那一項可用帳戶原則來設定？  ', '與印表機的連線  ', '密碼長度  ', '連線網路資源  ', '桌面設定？', '', '2');
INSERT INTO `data` VALUES (478, 27, '下列何者不是微軟推薦的結構化問題排除方法中的步驟？  ', '排定優先次序  ', '重新載入作業系統和應用程式  ', '收集資訊  ', '測試並隔離問題。', '', '2');
INSERT INTO `data` VALUES (479, 27, '系統時鐘是用那個IRQ？  ', '0  ', '2  ', '5  ', '7。', '', '1');
INSERT INTO `data` VALUES (480, 27, 'LPT1用的是那個IRQ？', '0  ', '2  ', '5  ', '7。', '', '4');
INSERT INTO `data` VALUES (481, 27, '那個裝置和COM1共用IRQ4？  ', 'COM2  ', 'COM3  ', 'COM4  ', 'LPT2。', '', '2');
INSERT INTO `data` VALUES (482, 27, 'COM2用的是那個  ？  ', '0  ', '2  ', '3  ', '4。', '', '3');
INSERT INTO `data` VALUES (483, 27, '那個裝置可測試信號是否有通過纜線？  ', '電表  ', '時間-區間分析儀  ', '示波器  ', '協定分析儀。', '', '2');
INSERT INTO `data` VALUES (484, 27, '那個裝置可測試纜線電壓狀態？  ', '電表  ', '時間-區間分析儀  ', '示波器  ', '協定分析儀。  ', '', '1');
INSERT INTO `data` VALUES (485, 27, '那個裝置又稱為sniffer？  ', '電表  ', '時間-區間分析儀  ', '示波器  ', '協定分析儀(網路分析儀) 。', '', '4');
INSERT INTO `data` VALUES (486, 27, '協定分析儀不能偵測下列那種問題？  ', '有問題的網路卡  ', '纜線問題  ', '協定設定錯誤  ', '纜線電壓。', '', '4');
INSERT INTO `data` VALUES (487, 27, '若網路上只有一個系統出問題，應先檢查那個部分？  ', '伺服器  ', '集線器  ', '介面卡  ', '網路裝置。', '', '4');
INSERT INTO `data` VALUES (488, 27, '下列何者為數據機(modem)之功能？  ', '二進位數與十進位數互作轉換  ', '數位與類比訊號互作轉換  ', '同步與非同步訊號互做轉換  ', 'EBCDIC碼ASCII碼互坐轉換。', '', '2');
INSERT INTO `data` VALUES (489, 27, '調變器(MODEM)之用途為：  ', '與大哥大相似，可發射與接受信號  ', '可以改變信號的波形  ', '接收人造?星(Satellite)電視轉播  ', '能夠改變資料上的密碼。', '', '2');
INSERT INTO `data` VALUES (490, 27, '下列何者可以傳遞電腦資訊或電子訊號於兩地間？  ', '可攜式筆記電腦  ', '傳真機  ', '電話線  ', '以上皆是 。', '', '3');
INSERT INTO `data` VALUES (491, 27, 'MODEM主要用來？  ', '安裝在電腦內部  ', '打電話  ', '輸出資料  ', '調變／解調 。', '', '4');
INSERT INTO `data` VALUES (492, 27, '將數位訊號轉換成類比訊號的過程為？  ', '調變(Modulation)  ', '通訊(Communication)  ', '解調(Demodulation)  ', '傳輸(Transmitting) 。', '', '1');
INSERT INTO `data` VALUES (493, 27, '個人電腦透過電話線通訊時，需下列那種通訊控制設備？  ', '數位機(MODEM)  ', '前端機率(FEP)  ', '多工機(Multiplier)  ', '集訊機(Concentrator) ', '', '1');
INSERT INTO `data` VALUES (494, 27, '下列何種傳輸介質可不受電磁干擾？  ', '絞線(twisted pair)  ', '同軸電纜(coaxial)  ', '微波(microwave)  ', '光纖(optical) 。', '', '4');
INSERT INTO `data` VALUES (495, 27, '電腦連接數位機透過傳輸線和他方的電腦相連，通常此傳輸線為下列何者？  ', '類比電話線  ', '數位電話線  ', '紅外線  ', '紫外線 。', '', '1');
INSERT INTO `data` VALUES (496, 27, '電腦通訊傳輸速率，通常以什麼為單位？  ', 'MIPS  ', 'BPS  ', 'KB  ', 'NS(nanocecond) 。', '', '2');
INSERT INTO `data` VALUES (497, 27, '若以9600BPS的傳輸速率傳送6000個BIG-5碼中文字，需多少時間？  ', '0.625秒  ', '1.6秒  ', '5秒  ', '10秒 。', '', '4');
INSERT INTO `data` VALUES (498, 27, '資料的傳輸方式中，可在同一時間中做不同的方向的資料傳輸，即雙方均能同時做接收及傳輸資料工作，稱為：  ', '單工(Simplex)  ', '半雙工(Half Duplex)  ', '全雙工(Full Duplex)  ', '以上皆非 。', '', '3');
INSERT INTO `data` VALUES (499, 27, '打電話是屬於何種傳輸方式？  ', ' 單工(Simplex)  ', '半雙工(Half Duplex)  ', '全雙工(Full Duplex)  ', '並列傳輸(Parallel) 。', '', '3');
INSERT INTO `data` VALUES (500, 27, '平行埠(Parallel Port)每次可送出多少字元(Character)？  ', '1  ', '2  ', '3  ', '4 。', '', '1');
INSERT INTO `data` VALUES (501, 27, '在區域網路中，通常資料的傳輸是採用？  ', '串列方式  ', '並列方式  ', '串列與並列混合方式  ', '以上皆非 。', '', '1');
INSERT INTO `data` VALUES (502, 27, '通常在非同步(asynchronous)串列資料傳送中使用的輸出入(I/O)控制元件，在規劃傳輸模式時，下列何者可有可無？  ', '停止位元(stop bit)  ', '開始位元(start bit)  ', '錯誤檢查用的同位位元(parity bit)  ', '資料位元(information bit) 。', '', '3');
INSERT INTO `data` VALUES (503, 27, '兩臺電腦經由電話線傳送資料，資料以何種方式傳送？ ', 'serial  ', 'parallel  ', 'DMA  ', 'bus 。', '', '1');
INSERT INTO `data` VALUES (504, 22, '電腦資料最小儲存單位僅能儲存二進位值0或1，此儲存單位稱為? ', '位元(Bit) ', '位元組(Byte) ', '字組 ', '字串', '', '1');
INSERT INTO `data` VALUES (505, 22, '位元的個人電腦，一個位元組(byte)是由幾個位元(bit)組成? ', '4 ', '8 ', '16 ', '32', '', '2');
INSERT INTO `data` VALUES (506, 22, '位元電腦之字組(word)長為 ', '2 bytes ', '4 bytes ', '16 bytes ', '32 bytes', '', '2');
INSERT INTO `data` VALUES (507, 22, '下列有關電腦儲存資料的單位，何者儲存容量最大? ', '1 Byte ', '1 Kilo Byte ', '1 Mega Byte ', '1 Giga Byte', '', '4');
INSERT INTO `data` VALUES (508, 22, 'MB(Mega Bytes)等於多少個Bytes? ', '1024K', '2024K ', '512K ', '256K', '', '1');
INSERT INTO `data` VALUES (509, 22, '通常記憶體的容量是以位元組(Byte)為單位，試問一 Kilo Bytes 是2 的幾次方? ', '12 ', '14 ', '10 ', '20', '', '3');
INSERT INTO `data` VALUES (510, 22, '我們稱記憶容量為2GB(Giga Bytes)，其容量相當於 ', '2048KB ', '2048MB ', '1024KB ', '1024MB', '', '2');
INSERT INTO `data` VALUES (511, 22, '下列敘述何者正確? ', '1GB>1MB>1KB ', '資料欄通常由數個資料錄所組成    ', '1KB=210Byte ', 'Byte為電腦儲存資料的最基本單位', '', '1');
INSERT INTO `data` VALUES (512, 22, '下列敘述何者正確? ', '1KB=1024bytes ', '1KB=1000bytes ', '1MB=1000Kbytes ', '1MB=216bytes', '', '1');
INSERT INTO `data` VALUES (513, 22, '電腦儲存資料的單位中1GB(Giga Bytes)等於多少? ', '1024MB ', '1024KB ', '1024B ', '240Bytes', '', '1');
INSERT INTO `data` VALUES (514, 22, '所謂640KB記憶體，是指記憶體容量為 ', '640x1000 Bytes ', '640x1024 Bytes ', '640x1000 Bits ', '640x1024 Bits', '', '2');
INSERT INTO `data` VALUES (515, 22, '下列關於KB, MB, GB 何者錯誤? ', '1KB < 1GB ', '1MB = 1024KB ', '1GB = 1024KB ', '1KB = 1024B', '', '3');
INSERT INTO `data` VALUES (516, 22, '若人與電腦間的資料溝通只用26個大寫英文字母，則電腦每個字元最多只需幾個Bit即可表達? ', '3 ', '4 ', '5 ', '6', '', '3');
INSERT INTO `data` VALUES (517, 22, '某計算機有24K記憶體，若第一個位元組之位址為0000，則最後一個位元組之位址(十六進位)為    ', '6000 ', '5FFF ', '5DBF ', '5DC0', '', '2');
INSERT INTO `data` VALUES (518, 22, '表示一個英文字母、數字或特殊符號是 ', '位元(Bit) ', '位元組(Byte) ', '欄(Field) ', '資料記錄(Record)', '', '2');
INSERT INTO `data` VALUES (519, 22, '衡量CPU執行速度單位為 ', 'MIPS ', 'BPS ', 'CPS ', 'BPI', '', '1');
INSERT INTO `data` VALUES (520, 22, '評估電腦執行速度常用的單位為 ', 'BYTE ', 'IPS ', 'BPI ', 'MIPS', '', '4');
INSERT INTO `data` VALUES (521, 22, '下列何者為電腦網路系統中資料的傳輸單位? ', 'CPI ', 'BPS ', 'CPS (D', '', '', '2');
INSERT INTO `data` VALUES (522, 22, '數據傳輸的頻率單位為 ', 'BPI ', 'MBPS ', 'MBPM ', 'MBPH', '', '2');
INSERT INTO `data` VALUES (523, 22, ')BPI以28800 BPS 的傳輸速率傳送1.44 Mbytes 的資料約需時多久? ', '50秒 ', '200秒 ', '400秒 ', '2000秒', '', '3');
INSERT INTO `data` VALUES (524, 22, '英代爾公司(Intel)研發的 Pentium 120 處理機，其 120 代表什麼單位? ', 'MHz ', 'MIPS ', 'BPS ', 'TPI', '', '1');
INSERT INTO `data` VALUES (525, 22, '雷射印表機的規格上註明 600DPI 指的是什麼? ', '列印速度 ', '解析度 ', '色彩種類 ', '置放紙張數', '', '2');
INSERT INTO `data` VALUES (526, 22, '磁帶儲存資料的計算單位為 ', 'BPI ', 'QIC ', 'DAT ', 'MCI', '', '1');
INSERT INTO `data` VALUES (527, 22, '下列那個敘述是錯的? ', '任何十進位整數都可用二進位表示 ', '任何十進位小數都可用二進位表示', '任何二進位整數都可用十進位表示 ', '任何二進位小數都可用十進位表示', '', '2');
INSERT INTO `data` VALUES (528, 22, '八進位是由幾個二進位組成 ', '3 ', '5 ', '6 ', '8', '', '1');
INSERT INTO `data` VALUES (529, 22, '下列何者為十六進位系統中最大的數 ', 'A ', 'D ', 'G ', 'F', '', '4');
INSERT INTO `data` VALUES (530, 22, '十進位的"43"在二進位中是以 ', '101011 ', '100101 ', '110101 ', '101001 表示', '', '1');
INSERT INTO `data` VALUES (531, 22, '十進位的"13"在十六進位中是以 ', 'C ', 'D ', 'E ', 'F 表示', '', '2');
INSERT INTO `data` VALUES (532, 22, '二進位制(01101101)與下列何者十六進位數相等 ', '(67) ', '(155) ', '(100) ', '(6D)', '', '2');
INSERT INTO `data` VALUES (533, 22, '二進位的11101111在十進位中以下列何者表示 ', '239 ', '240 ', '242 ', '246', '', '1');
INSERT INTO `data` VALUES (534, 22, '二進位數值(101011)的值相當於十進位多少 ', '41 ', '43 ', '51 ', '53', '', '1');
INSERT INTO `data` VALUES (535, 22, '十六進位數系的(FF)，以十進位數系表示等於 ', '102 ', '255 ', '238 ', '272', '', '2');
INSERT INTO `data` VALUES (536, 22, '十六進位的(AB)以十進位數表示是 ', '171 ', '170 ', '160 ', '182', '', '1');
INSERT INTO `data` VALUES (537, 22, '整數25以2個byte的定點數表示時，其十六進位數值為 ', '0019 ', '0020 ', '001A ', '001B', '', '1');
INSERT INTO `data` VALUES (538, 22, '十進位數(93.875)等於八進位數 ', '(135.7) ', '(153.7) ', '(173.5) ', '(157.3)', '', '1');
INSERT INTO `data` VALUES (539, 22, '二進位(1101.101)轉換成十進位制的值為 ', '26.35 ', '26.625 ', '13.35 ', '13.635', '', '4');
INSERT INTO `data` VALUES (540, 22, '下列何者為八進位制(537.5)的二進制值 ', '101011111.101 ', '101010111.011 ', '110011111.101 ', '101011111.100', '', '1');
INSERT INTO `data` VALUES (541, 22, '將八進位數值(7532.64)轉成十六進位是多少 ', 'F5A.D ', 'F5A.34 ', '3766.32 ', '941.58', '', '1');
INSERT INTO `data` VALUES (542, 22, '將八進位數值(25.7)轉換成十六進位數，其結果為 ', '14.7 ', '13.E ', '15.7 ', '15.E', '', '4');
INSERT INTO `data` VALUES (543, 22, '假設我們習慣使用5進位和4進位的數字系統，則(1324)?與下列四進位何值相等?    ', '(3002) ', '(3012) ', '(3112) ', '(2121)', '', '3');
INSERT INTO `data` VALUES (544, 22, '電腦的二進制數字系統，其負數是以何種方法表示 ', '負數 ', '浮點數法 ', '分數法 ', '2補數法', '', '4');
INSERT INTO `data` VALUES (545, 22, '計算機之減法由下列何種方法執行 ', '被減數與減數相加 ', '減數減去被減數 ', '被減數減去減數 ', '計算補數後相加', '', '4');
INSERT INTO `data` VALUES (546, 22, '之1的補數表示法為 ', '11101100 ', '00010101 ', '00010100 ', '00011010', '', '3');
INSERT INTO `data` VALUES (547, 22, '二進位數1001之2''補數為 ', '0111 ', '1001 ', '1111 ', '0110', '', '1');
INSERT INTO `data` VALUES (548, 22, '十六進位數字1B，其二的補數表示法的值為 ', 'E4 ', 'E5 ', 'FB ', 'B1', '', '2');
INSERT INTO `data` VALUES (549, 22, '設一電子計算機系統"2的補數"代表負數值，請問在此系統中(010110)', '010011 ', '010100 ', '101101 ', '101100', '', '3');
INSERT INTO `data` VALUES (550, 22, '假設某電腦系統以8位元表示一個整數，而負數採用2的補數表示方式，則十進位數(-30)的二進位表示法應該為何?    ', '11100010 ', '11100001 ', '00011110 ', '10011110', '', '1');
INSERT INTO `data` VALUES (551, 22, '若某電腦系統以8位元表示一個整數，且負數採用2的補數方式表示，則(10010111)', '149 ', '116 ', '-106 ', '-105', '', '4');
INSERT INTO `data` VALUES (552, 22, '一計算機若以2的補數法來表示數值，則下列的二進制數值，何者相當於十進制的-127    ', '01111111 ', '10000000 ', '10000001 ', '1111111', '', '3');
INSERT INTO `data` VALUES (553, 22, '下列何者可以表示八位元電腦中的-10 (以2的補數法示) ', '10001010 ', '00001010 ', '11110101 ', '11110110', '', '4');
INSERT INTO `data` VALUES (554, 22, '某一電腦系統以8位元表示整數，負數以2的補數表示，則-78應為下列何者?    ', '11010101 ', '10110010 ', '10110001 ', '10010011', '', '2');
INSERT INTO `data` VALUES (555, 22, '若系統使用二的補數法來儲存負數，將十進位數-17轉換為八位元之二進位表示時，正確值應為    ', '00010001 ', '11101110 ', '11101111 ', '00010000', '', '3');
INSERT INTO `data` VALUES (556, 22, '有八位元的整數，以十六位元表示為F5，在2''S補數法中應是 ', '-10 ', '-11 ', '-12 ', '-13        ', '', '2');
INSERT INTO `data` VALUES (557, 22, '以8位元表示一整數，若用2的補數表示負數，則表示範圍是 A)-127～128 ', '-128～127 ', '-127～127 ', '-128～128', '', '', '2');
INSERT INTO `data` VALUES (558, 22, '陣列宣告 DIM A(10)，則陣列A內有幾個元素 ', '9 ', '10 ', '11 ', '12', '', '3');
INSERT INTO `data` VALUES (559, 22, '在BASIC中，DIM ARRAY1(3,4) 宣告ARRAY1陣列是一個二維陣列，它包含幾個元素 ', '2 ', '7 ', '12 ', '20', '', '4');
INSERT INTO `data` VALUES (560, 22, '在二維陣列中宣告 DIM A(3,3) 記憶體會預留多少個元素空間 ', '10 ', '6 ', '9 ', '16', '', '4');
INSERT INTO `data` VALUES (561, 22, '在BASIC中，宣告陣列 DIM A(2,3,4)，則共可使用多少個陣列元素 ', '24 ', '6 ', '60 ', '120       ', '', '3');
INSERT INTO `data` VALUES (562, 22, 'X=1 : Y=2 : Z=3      20 DIM A(X,Y,Z)在BASIC中，宣告 DIM A%(3,3)，佔用多少位元組的記憶體位址 ', '9 ', '16 ', '32 ', '64', '', '3');
INSERT INTO `data` VALUES (563, 22, '在BASIC中，宣告 DIM A!(3,3)，佔用多少位元組的記憶體位址 ', '9 ', '16 ', '32 ', '64              ', '', '4');
INSERT INTO `data` VALUES (564, 22, '下列那一項BASIC的陣列宣告方式錯誤', 'DIM ARR1(2,10,20) ', 'DIM ARR1(2),ARR1(10,20)', 'DIM ARR1(2),ARR2(10,20) ', 'DIM ARR%(2),ARR%(10,20)', '', '2');
INSERT INTO `data` VALUES (565, 22, '宣告陣列 DIM X(20)，則下列何者語法錯誤 \n', 'X(5)=100 ', 'X(1)="HELLO"', 'X(20)=X(8)*X(16)', 'Y=RND(3)*X(10)', '', '2');
INSERT INTO `data` VALUES (566, 22, '下列何者用來存取陣列中的資料 ', '資料庫 ', '註標 ', '檔案 ', '以上皆非', '', '2');
INSERT INTO `data` VALUES (567, 22, '若使用 OPTION BASE 1，則 DIM A(3,4) 中的陣列A最多可存多少個陣列元素 ', '12 ', '15 ', '16 ', '20', '', '1');
INSERT INTO `data` VALUES (568, 22, '欲清除記憶體中某陣列所佔的空間，可使用那一個指令 ', 'CLEAR ', 'HOME ', 'OPTION BASE ', 'ERASE', '', '4');
INSERT INTO `data` VALUES (569, 22, '在程式設計工具中，以使用類似英文的敘述表示程式的邏輯流程，謂之 ', '流程圖 ', '甘特圖 ', '虛擬碼 ', '卡諾圖', '', '3');
INSERT INTO `data` VALUES (570, 22, '在流程圖中，決策判斷的圖形為 ', '菱形 ', '矩形 ', '圓形 ', '橢圓形', '', '1');
INSERT INTO `data` VALUES (571, 22, '下列何者不是使用流程圖的好處 ', '有助於除錯 ', '有助於程式設計師與使用者之溝通    ', '可減少程式設計之錯誤 ', '可以控制程式撰寫時間', '', '4');
INSERT INTO `data` VALUES (572, 22, '用以表示作業範圍與作業體系的流程圖是 ', '程式流程圖 ', '明細流程圖 ', '系統流程圖 ', '程序流程圖', '', '3');
INSERT INTO `data` VALUES (573, 22, '檔案(FILE)是由多個性質相關的 ', '資料欄 ', '記錄 ', '位元組 ', '資料庫 所組成', '', '2');
INSERT INTO `data` VALUES (574, 22, '假設 1.FIELD 2.RECORD 3.BIT 4.CHARACTER，則其在計算機內所佔空間大小，由小到大之順序為    ', '1234 ', '3412 ', '4321 ', '3142', '', '2');
INSERT INTO `data` VALUES (575, 22, '資料檔的組織係指資料記錄在資料檔儲存方式，則下列何種檔案組織最節省記憶空間?    ', '直接式 ', '相關式 ', '循序式 ', '索引式', '', '3');
INSERT INTO `data` VALUES (576, 22, '下列那一種電腦資料存取方法的平均速度為最慢 ', '隨機存取法 ', '索引存取法 ', '順序存取法 ', '直接存取法', '', '3');
INSERT INTO `data` VALUES (577, 22, '下列何者是BASIC中循序檔的特性 ', '檔案更新處理時，須另外產生新的主檔 ', '適合直接存取 ', '適合即時處理使用    ', '可以迅速的查詢任意資料', '', '1');
INSERT INTO `data` VALUES (578, 22, '關於BASIC程式語言的隨機檔案，下列敘述何者不正確 ', '隨機檔案僅能讀取資料無法寫入資料 ', '隨機檔案處理效率    比循序檔案方便 ', '資料錄的長度固定不變 ', '可用OPEN敘述開啟檔案', '', '1');
INSERT INTO `data` VALUES (579, 22, '資料檔之每一筆記錄均為固定長度，存入或取出資料時，只要指明第幾筆記錄，則該資料檔是為    ', '循序檔 ', '程式檔 ', '隨機檔 ', '以上皆非', '', '3');
INSERT INTO `data` VALUES (580, 22, '若要隨機存取檔案中之記錄，下列何種檔案速度最快 ', '循序檔 ', '索引檔 ', '隨機檔 ', '磁帶檔', '', '3');
INSERT INTO `data` VALUES (581, 22, '在檔案操作中，存取檔案的資料，其步驟為 ', '關檔、開檔、存取 ', '存取、開檔、關檔    ', '開檔、關檔、存取 ', '開檔、存取、關檔', '', '4');
INSERT INTO `data` VALUES (582, 22, 'BASIC程式開啟循序檔案的模式，不包括下列哪一項 ', 'RANDOM(R) ', 'INPUT(I) ', 'OUTPUT(O) ', 'APPEND', '', '1');
INSERT INTO `data` VALUES (583, 22, '數據通信系統中，傳輸網路兩端之節點可以在同一時間互相傳輸及接受資料的方式稱為    ', '全雙工式 ', '半雙工式 ', '單工式 ', '倍雙工式', '', '1');
INSERT INTO `data` VALUES (584, 22, '可做雙向資料傳輸，但無法同時雙向傳輸的資料通訊方式是 ', '單工 ', '半雙工 ', '全雙工 ', '倍雙工', '', '2');
INSERT INTO `data` VALUES (585, 22, '在區域網路中，通常資料的傳輸是採用 ', '串列方式 ', '並列方式 ', '串列與並列混合方式', '', '', '1');
INSERT INTO `data` VALUES (586, 22, '目前(台視、中視、華視)三家電視台的電視廣播節目之資料通訊傳輸模式為    ', '全雙工傳輸 ', '半雙工傳輸 ', '單工傳輸 ', '全雙工傳輸和半雙工傳輸', '', '3');
INSERT INTO `data` VALUES (587, 22, '在日常生活中，電視台至家中電視是採用何種傳輸方式 ', '單工 ', '半雙工 ', '全雙工 ', '以上皆是   ', '', '1');
INSERT INTO `data` VALUES (588, 22, '計算機與印表機間的資料傳輸屬下列何者 ', '單工 ', '半雙工 ', '全雙工 ', '多工', '', '1');
INSERT INTO `data` VALUES (589, 22, '當網路在傳輸資料時，傳輸方式若以其類型區分，下列何者不屬其傳輸類型 ', '單工 ', '半雙工 ', '全雙工 ', '多工', '', '4');
INSERT INTO `data` VALUES (590, 22, '以2400BPS來傳送檔案資料，而傳送一個位元組另需一個起始位元與一個停止位元，當傳送4K位元組的檔案約需多少秒    ', '13.07 ', '13.65 ', '16.67 ', '17.06', '', '4');
INSERT INTO `data` VALUES (591, 22, '資料通訊傳輸速度單位為 ', 'BPI ', 'CPI ', 'BPS ', 'CPS', '', '3');
INSERT INTO `data` VALUES (592, 22, '下列何者屬於數據通訊常用的設備 ', '數據機 ', '通訊控制單元 ', '通訊線路 ', '以上皆是', '', '4');
INSERT INTO `data` VALUES (593, 22, '下列何種結構，不是網路結構的一種 ', '星狀結構 ', '分散型結構 ', '環狀結構 ', '網狀結構   ', '', '2');
INSERT INTO `data` VALUES (594, 22, '下列區域網路架構中，具廣播特性，且任何一部電腦將資料傳送上電纜線後，其訊號會向兩端傳遞，如有任一部電腦    故障，仍不會影響其他電腦之間通訊的是 ', '星狀 ', '匯流排 ', '環狀 ', '網狀架構', '', '2');
INSERT INTO `data` VALUES (595, 22, '下列網路架構中，那一種會因電腦有問題，而導致網路中所有電腦都無法聯繫 ', '星狀 ', '環狀 ', '樹狀 ', '匯流排', '', '2');
INSERT INTO `data` VALUES (596, 22, '有關區域網路的敘述，下列那一項敘述不正確 ', '短距離的通訊網路 ', '資料傳輸效率高    ', '軟硬體資源共享 ', '無法作電子郵件之傳送', '', '4');
INSERT INTO `data` VALUES (597, 28, '汽車、機車、單車尾部常裝設的反光片，其內部設計為 ', '多個凸透鏡的組合 ', '多個凹透鏡的組合 ', '多個凸面鏡的組合 ', '多個凹面鏡的組合 ', '多個平面反射面的組合。', '5');
INSERT INTO `data` VALUES (598, 28, '下列何者錯誤？ ', '超導是指電阻為0，磁導率無限大的完全反磁性 ', 'IC是由半導體的晶片組成 ', '雷射是由原子能態躍遷產生 ', '1公尺是由光在真空中走極短時間所走長度定義出的 ', '光度的國際基本單位為燭光', '1');
INSERT INTO `data` VALUES (599, 28, '密度為ρ1與ρ2的兩液體，且ρ1大於ρ2，則下列何者正確？ ', '取等質量混合後（假定體積守守恆），混合密度為(ρ1 ρ2)/2  ', '取等體積混合後（假定體積守守恆），混合密度為2(ρ1ρ2)/(ρ1 ρ2)  ', '兩液體任意混合，密度值可以為任意數 ', '等體積混合的密度比等質量混合的密度大。', '', '4');
INSERT INTO `data` VALUES (600, 28, '密度d、質量m、體積v，由關係式d＝(m/v)下列何者正確？ ', '密度與質量成正比 ', '密度與體積成正比 ', '質量與體積成正比 ', '密度與體積的乘積為一定值 ', '密度與質量的比值為一定值（以上均以同一物質而言）。', '4');
INSERT INTO `data` VALUES (601, 28, '已知酒精密度為0.8g/cm3，水的密度為1.0 g/cm3，若已知混合液質量為600g，混合液體積為700cm3，假設混合時體積可加成，請問混合液中水和酒精的體積比為 ', '1：1 ', '2：5 ', '4：3 ', '6：7。', '', '2');
INSERT INTO `data` VALUES (602, 28, '密度各為8、12之A、B兩金屬，取等質量製成合金，則合金之密度為？ ', '10 ', '9.6 ', '15 ', '20。', '', '2');
INSERT INTO `data` VALUES (603, 28, '假設光一秒鐘可行300000km，約可繞地球7.5圈，試推算地球半徑約為若干？ ', '8640 ', '4320 ', '6400 ', '12960 km。', '', '3');
INSERT INTO `data` VALUES (604, 28, '某組同學用同一種方法測量同一塊鐵的密度五次，數據為7.8，7.9，7.9，8.0，8.9；則鐵的平均密度的合理表示法應為下列何者？〔單位為g/cm3〕 ', '7.8 ', '7.9 ', '8.0 ', '8.1。', '', '2');
INSERT INTO `data` VALUES (605, 28, '以一把尺，量測某物體之長度，所得之長度值為18.21公尺。則該尺之最小刻度為 ', '公尺 ', '公寸 ', '公分 ', '公厘（釐）。', '', '2');
INSERT INTO `data` VALUES (606, 28, '假定有某個物理量x可表為x＝ky＋z，則 ', 'x與k的單位須相同 ', 'x與y的單位須相同 ', 'x與z的單位須相同 ', 'x與ky的數量須相同 ', 'x與z的數量須相同。', '5');
INSERT INTO `data` VALUES (607, 28, '有AB兩支單擺，已知A擺的頻率為B擺的兩倍。今已A擺作為計時的基準，且規定其擺動105次的時間為1日，則當B擺擺動105次，所經過的時間為 ', '0.5 ', '1.0 ', '1.5 ', '2.0 ', '4.0 日。', '2');
INSERT INTO `data` VALUES (608, 28, '選手以2公尺／秒2的加速度由靜止起跑，跑完100公尺，其平均速率為多少公尺／秒？ ', '5 ', '10 ', '15 ', '20。', '', '2');
INSERT INTO `data` VALUES (609, 28, '下列何者的方向和其他者不同？ ', '力 ', '速度 ', '速度變化量 ', '加速度。', '', '2');
INSERT INTO `data` VALUES (610, 28, '一人在屋頂上用繩子將一重24公斤之物體往上拉，若人以264N之力量拉動繩子，繩子重量不計，則該物體上升之加速度為何？ ', '2.4 ', '0.6 ', '1.2 ', '11 m/s2。', '', '3');
INSERT INTO `data` VALUES (611, 28, '一工人站在屋頂上，利用繩子欲將一水桶拉上來。已知水桶的總質量為24公斤，該工人以245牛頓的力量拉動繩子，若不計繩子的重量，則水桶上升的加速度為何？ ', '10.2 ', '0.41 ', '12 ', '0.51 公尺／秒2。（g＝9.8公尺／秒2）', '', '2');
INSERT INTO `data` VALUES (612, 28, '一物體的質量為2kg，由靜止開始受一定力作用，使其在光滑的水平面上運動；若7秒後之速度為21m/s，則作用在物體上的外力為 ', '6 ', '10.5 ', '42 ', '7 N。', '', '1');
INSERT INTO `data` VALUES (613, 28, '一鉛直懸掛的彈簧下端懸掛一秤盤，上面放置砝碼作「虎克定律」實驗時，每個砝碼質量均為10g，實驗數據如右表所示，則下列敘述何者錯誤？ ', '只懸掛秤盤時，彈簧之伸長量為1.2cm ', '當砝碼數為7個時，彈簧伸長量為2.6cm ', '秤盤之質量為40g ', '掛10個砝碼時，彈簧可能已經超過彈性限度。', '', '3');
INSERT INTO `data` VALUES (614, 28, '一輛公車發現前方有障礙物時，駕駛立即緊急煞車，在車子滑行的過程中，下面關於速度與加速度的敘述，何者正確？ ', '速度向前、加速度向後 ', '速度與加速度都向前 ', '速度與加速度有時同向，有時反向 ', '加速度恆為零。', '', '1');
INSERT INTO `data` VALUES (615, 28, '力常數為2gw/cm與1gw/cm的彈簧各一條，將兩條彈簧串聯的力常數為k1/K2；兩條彈簧並聯時的力常數為k2，則 為 ', '1/2  ', '2/3  ', '2/9  ', '3/5  ', '2/7 。', '3');
INSERT INTO `data` VALUES (616, 28, '物體所受的外力F與質量M、加速度A的關係為M＝F/A，則對一個特定的物體來說，其質量M ', '與外力F正比 ', '與加速度A成反比 ', '只與F/A的比值有關 ', '與F、a均無關 ', '只與F＋A有關。', '4');
INSERT INTO `data` VALUES (617, 28, '下列有關力與運動的說法，何者正確？ ', '物體的運動速度是由力來維持的 ', '物體所受的合力方向與速度同向 ', '物體的瞬時速度為零時，所受的合力也是零 ', '物體速度改變時，一定受到力的作用 ', '物體受力時，速率一定改變。', '4');
INSERT INTO `data` VALUES (618, 28, '一水平輸送帶恆以等速度v沿＋x方向移動，在時刻t＝0時，將一質量為m的箱子以水平速度u＝0置於輸送帶上，如附圖所示。若箱子與輸送帶之間的靜摩擦係數為μS，動摩擦係數為μK，重力加速度為g，則下列有關此箱子的敘述，何者正確？　', '摩擦力對箱子所做的總功為－0.5mv2　', '當t＝v/(μKg)時，箱子的速度會等於輸送帶的速度　', '在時刻t＝0時，箱子所受的淨力為μSmg，向＋x方向　', '在時刻t＝0時，箱子所受的淨力為μKmg，向－x方向　', '當箱子的速度等於v時，箱子所受的摩擦力為μSmg，向＋x方向', '2');
INSERT INTO `data` VALUES (619, 28, '甲、乙兩人體重各為60公斤重、40公斤重。各立於一彈簧秤上，彈簧秤以公斤重為刻度，今甲施10公斤重之力欲舉乙向上，則兩人所立之彈簧秤之秤數各為若干公斤重？　', ' 70，30　', '均為50　', ' 100，0　', ' 30，70　', '均為0公斤重', '1');
INSERT INTO `data` VALUES (620, 28, '熱氣球載有沙包2包時，以加速度2a上升；載有沙包8包時，則以加速度a下降。若不計氣球本身的重量及沙包的浮力，而欲使熱氣球以g/3的加速度上升時，應載沙包幾包？　', ' 3　', ' 4　', ' 5　', ' 6　', ' 7 ', '1');
INSERT INTO `data` VALUES (621, 28, '雨滴以3 m/s之速率垂直地面降下，雨量為每平方公尺2 kg/s，且雨滴撞擊物體後不反彈，則地面受力每平方公尺為多少牛頓？　', ' 1　', ' 2　', ' 3　', ' 4　', ' 6', '5');
INSERT INTO `data` VALUES (622, 28, '功的單位是　', '牛頓　', '焦耳　', '庫侖　', '達因', '', '2');
INSERT INTO `data` VALUES (623, 28, '後輪驅動的轎車在水平地面加速前進時，下列敘述何者正確？　', '前輪的摩擦力對轎車作正功　', '後輪的摩擦力對轎車作正功　', '前、後輪的摩擦力對轎車皆作正功　', '前、後輪的摩擦力對轎車皆作負功', '', '2');
INSERT INTO `data` VALUES (624, 28, '一人造衛星繞地球作等速率圓周運動，下列敘述何者正確？　', '衛星所受的合力為零，所以速率維持不變　', '衛星受來自地球的吸引力，此力用於改變衛星的運動方向　', '衛星的加速度為零　', '衛星所受的向心力作正功，以維持衛星的動能不變', '', '2');
INSERT INTO `data` VALUES (625, 28, '用繩垂直放下一質量為M之木塊，以g/4之等加速度下降d之距離，繩對木塊所作之功為：　 ', ' Mgd/4　', ' Mgd/2　', ' 3Mgd/4　', '－Mgd/4　', '－3Mgd/4', '5');
INSERT INTO `data` VALUES (626, 28, '由n張葉片製成的百葉窗（葉片厚度不計），掛下時每張葉片相距s，若每片質量為M，則全部窗簾拉上需做功為　', ' Mgs　', ' nMgs　', ' (n＋1)Mgs　', ' n(n＋1)Mgs　', ' 1/2n(n 1)Mgs', '5');
INSERT INTO `data` VALUES (627, 28, '某機器在40 s內將200 kgw的重物舉高30 m，求平均功率為多少瓦特？　', ' 1470　', ' 150　', ' 720　', ' 2400　', ' 60', '1');
INSERT INTO `data` VALUES (628, 28, '質量500公克的棒球由樓頂水平拋出，經2秒落地，則全程重力對棒球所作之功為多少焦耳？（g＝10 m/s2）　', ' 100　', ' 200　', ' 400　', ' 500　焦耳', '', '1');
INSERT INTO `data` VALUES (629, 28, '一個在水平地面上的箱子，當受到的水平推力為F時（F＞0），以2公尺／秒的等速度向前移動。若地面摩擦力以外的阻力可以不計，則下列敘述，何者正確？　', '當推力為F時，箱子會以4公尺／秒的等速度移動　', '當箱子等速度移動時，推力F所做的總功為零　', '推力F的大小必須大於箱子所受的摩擦力　', '推力F的大小等於箱子所受的摩擦力　', '推力F的大小必須大於箱子的重量', '1');
INSERT INTO `data` VALUES (630, 28, '一彈簧的彈力常數為200 N/m，原來已伸長10公分，若欲將此彈簧在彈性限度內再伸長10公分，須做功多少焦耳？　', ' 0.75　', ' 1.0　', ' 2.0　', ' 3.0', '', '4');
INSERT INTO `data` VALUES (631, 28, '欲使一部時速108公里，車重1500公斤的BMW停止，地面施於輪胎摩擦力需作多少負功？　', ' 6.75×105　', ' 8.25×105　', ' 4.5×105　', ' 2.15×105　焦耳。', '', '4');
INSERT INTO `data` VALUES (632, 28, '速度為200 m/s的子彈，恰可射穿1 cm厚的固定木板；若欲射穿厚9 cm的木板(假設子彈所受的阻力不變)，子彈的速度最小應為多少m/s？　', ' 200　', ' 400　', ' 600　', ' 800', '', '4');
INSERT INTO `data` VALUES (633, 28, '下列有關力學中功能的敘述，何者錯誤？　', '力學能守恆告訴我們：所有不同形式的能量可以互相轉換，其總值不變　', '功－能定理就是說：力對物體所作的功等於物體動能的改變量　', '物體作圓周運動，向心力不作功　', '功率就是單位時間內所作的功', '', '3');
INSERT INTO `data` VALUES (634, 28, '在20公尺高處，某人拋出一個質量為2.0 kg的物體，物體離手時的速度是15 m/s，則人在拋擲時對物體作功是：　', ' 175 J　', ' 225 J　', ' 400 J　', ' 600 J　', '750 J', '3');
INSERT INTO `data` VALUES (635, 28, '輕繩繫一小球在水平面上作半徑0.5米之等速率圓周運動，已知小球受向心力為10 N，則小球的動能為若干焦耳？　', ' 2.5　', ' 5　', ' 10　', ' 20　', ' 40', '4');
INSERT INTO `data` VALUES (636, 28, '質量為m之物體，在高度h、斜角θ的斜面上，恰可等速下滑；今將斜角變為2θ，斜面長不變，則物體靜止由斜面頂滑至底端時動能為：　', ' mgh　', ' mgh sinθ　', ' mgh tanθ　', ' mgh secθ　', ' mgh cscθ', '4');
INSERT INTO `data` VALUES (637, 28, '一質量2.0公斤的物體放在水平桌面上，物體與桌面間的滑動摩擦係數為0.25。今以6.0牛頓的力沿水平方向推動物體，使物體作加速度運動，當物體移動5.0公尺時，此物體的動能約增加多少焦耳？　', ' 30　', ' 15　', ' 10　', ' 5　', ' 2', '4');
INSERT INTO `data` VALUES (638, 28, '將一顆球垂直向上拋出，當球到達最高點時，下列何者滿足當時的速度與加速度？ ', '速度與加速度都是零 ', '速度為零，加速度不為零 ', '速度不為零，加速度為零 ', '速度與加速度都不為零。', '', '2');
INSERT INTO `data` VALUES (639, 28, '有一人在地面上以45°仰角逆風將一球拋出，設風在水平方向，其阻力恰等於小球的重量，則此小球的軌跡為 ', '直線 ', '拋物線 ', '雙曲線 ', '橢圓 ', '正圓。', '1');
INSERT INTO `data` VALUES (640, 28, '光滑平面上有個靜止的木塊，今以水平定力F之，木塊移動的加速度為a；假如此木塊原來的初速不為零，例如其值為v0，則施加同樣的水平定力F於木塊上，木塊的加速度為 ', '0 ', 'Vo/2  ', 'v0 ', 'a ', 'a/2 。', '4');
INSERT INTO `data` VALUES (641, 28, '將力常數為1、2、3公斤重／公分的三條彈簧串聯起來，總力常數為 ', '6 ', '2 ', '1/3  ', '6/11  ', '7/5  ', '4');
INSERT INTO `data` VALUES (642, 28, '將地表上重量1公斤重的鉛球移到月球表面上，此時用磅秤量到的讀數為（月球表面的重力加速度為地表的1/6） ', ' 1/36 ', '1/6  ', '1 ', '6 ', '36 公斤重。', '2');
INSERT INTO `data` VALUES (643, 28, '一個密度均勻的星球，分裂為8個密度不變、質量相等的星球，則每個星球表面的重力加速度變為原來的多少倍？ ', '1/8  ', '1/4  ', '1/2  ', '2 ', '8。', '3');
INSERT INTO `data` VALUES (644, 28, '已知月球表面重力場強度為地球之六分之一，若在月球上進行托里切利實驗，則水銀柱之高度為在地球之幾倍？ ', '6 ', ' 1/6', '一樣高 ', '高度為零。', '', '4');
INSERT INTO `data` VALUES (645, 28, '地球半徑為R，阿華在地表上之重W；阿華坐飛機升至距地表0.5R的高空中，此時的重量減輕 ', 'W ', ' 2/3W ', ' 4/9W ', ' 5/9W。', '', '4');
INSERT INTO `data` VALUES (646, 28, '一太空船在半徑為2R的圓形軌道上環繞地球運動，R為地球的半徑。質量為60公斤的太空人在船內測得的視重為 ', '0 ', '15 ', '45 ', '60  公斤重。', '', '1');
INSERT INTO `data` VALUES (647, 28, '冠宏和爸媽去爬山，山的高度約為700公尺高，假設當時海平面氣壓為1大氣壓，又每升高100公尺，大氣壓力減少8公釐的水銀柱高度，則爬到山頂時，拿氣壓計量測，讀數應為多少？ ', '0.5大氣壓 ', '506.5毫巴 ', '704帕 ', '704公釐水銀柱。', '', '4');
INSERT INTO `data` VALUES (648, 28, '在馬德堡半球實驗中，若在操作的過程中，使用A、B、C三個不同直徑dA、dB及dC的銅製半球，若dA＞dB＞dC，則請問拉開兩個半球所需之力何者最大？ ', 'A ', 'B ', 'C ', '一樣大。', '', '1');
INSERT INTO `data` VALUES (649, 28, '下列有關人造衛星之敘述何者正確？ ', '軌道半徑越大之衛星其軌道速率越大 ', '某衛星從地面上看向東急行，所以其週期大於同步衛星之週期 ', '同步衛星之週期與極軸衛星的相同 ', '在同一個軌道上的兩個人造衛星必須具有一樣的質量才不會相撞 ', '同步衛星從地表看來，原地不動。', '5');
INSERT INTO `data` VALUES (650, 28, '在日常生活中，人們若欲利用抽水機將水由井中打上來，則水井不能太深，這最大抽水的深度約為 ', '1 ', '2 ', '5 ', '10 ', '20 公尺。', '4');
INSERT INTO `data` VALUES (651, 28, '下列有關摩擦力的敘述，何者正確？ ', '動摩擦力的大小與物體在接觸面上運動的快慢有關 ', '動摩擦力為定值 ', '靜摩擦力為定值 ', '將物體擺在極為粗糙的水平面上時，物體一定會受到靜摩擦力的作用。', '', '2');
INSERT INTO `data` VALUES (652, 28, '有一質量10公斤的物體置於斜角37之斜面上，若斜面的靜摩擦係數為0.8，動摩擦係數為0.5，重力加速度g＝10公尺／秒2。則物體與斜面之摩擦力為 ', '100 ', '80 ', '60 ', '40 ', '20  牛頓。', '3');
INSERT INTO `data` VALUES (653, 28, '質量為10公斤的木塊置於水平桌面上，其與桌面間之靜摩擦係數為0.2，若欲使此木塊移動，至少需用力若干牛頓？ ', '2 ', '9.8 ', '10.6 ', '19.6 ', '98。', '4');
INSERT INTO `data` VALUES (654, 28, '下列有關摩擦力的敘述，何者正確？ ', '動摩擦力的大小與物體在接觸面上運動的快慢有關 ', '動摩擦力為定值 ', '靜摩擦力為定值 ', '將物體擺在極為粗糙的水平面上時，物體一定會受到靜摩擦力的作用。', '', '2');
INSERT INTO `data` VALUES (655, 28, '某人欲在牆壁上釘畫框，他用手把畫框暫時壓在牆壁上，若畫框背面與牆壁間的靜摩擦係數為0.5，畫框重1公斤，則為避免畫框滑下，此人壓在畫框上的力至少應多大？ ', '5 ', '4 ', '3 ', '2 ', '1 公斤重。', '5');
INSERT INTO `data` VALUES (656, 28, '質量2公斤的物體，自高10公尺處自由落下，達地面一瞬間的功率為多少瓦特？　', ' 274.4　', ' 582.0　', ' 297.3　', ' 196.0', '', '1');
INSERT INTO `data` VALUES (657, 28, '一斜面長20 m，高10 m，今將沿斜面施以50 kgw之力，可把一90 kgw物體由斜面底等速推上至斜面頂，費時20秒，此力所作平均功率為多少瓦特？　', ' 490　', ' 980　', ' 245　', ' 441　', ' 50', '2');
INSERT INTO `data` VALUES (658, 28, '質量10公斤的水，自4.9公尺高的瀑布頂端自由落下，則達地面一瞬間的功率為多少瓦特？　', ' 960.4　', ' 582.0　', ' 297.3　', ' 196.0', '', '4');
INSERT INTO `data` VALUES (659, 28, '汽船引擎的輸出功率為4 kW，能使船以12 km／hr等速行駛，若阻力與船速成正比，船速增為24 km／hr，引擎功率變為若干kW？　', ' 4　', ' 8　', ' 12　', ' 16　', ' 64', '4');
INSERT INTO `data` VALUES (660, 28, '在直線的高速公路上，佳筠、思廷分別開車以等速度行駛，佳筠的速度為60 km／h，思廷落在佳筠的後方30 公里處，以80 km／h 的速度追趕，則思廷追上佳筠需費時多少小時？', '4/3', '2/3', '1/2', '3/2', '3/4。', '4');
INSERT INTO `data` VALUES (661, 28, '某一質點在直線上運動的x ? t 圖如右圖，質點於0～8 秒間平均速率為：', '5/4', '15/4', '25/4', '35/4', '45/4公尺／秒。', '2');
INSERT INTO `data` VALUES (662, 28, '菱菱投擲溜溜球(Yo-Yo 球)。溜溜球以每秒2 公尺的速率擲出，已知擲出至最低下降1 公尺後，以相同速率、相反方向回到她的手中(菱菱手的位置未變)，共經過2 秒鐘。則溜溜球自離開菱菱手中到再回到她手中的平均速率及平均加速度大小，各為X m／s 與Y m／s 2，試問下列哪一選項的數字可表示(X, Y)？', '(0, 1) ', '(1, 2) ', '(0, 2) ', '(1, 1)。', '', '2');
INSERT INTO `data` VALUES (663, 28, '若某人以20 km／h 的固定速率上山，循原路以30 km／h 的固定速率下山折返，則往返一趟的平均速率為何？', '0 ', '24 ', '25 ', '26km／h。', '', '2');
INSERT INTO `data` VALUES (664, 28, '印度豹是在陸地上跑得最快的動物，它的速度可快達113 km／h，能在4 秒內由靜止開始加速至速度72 km／hr。試問印度豹在這段加速過程中的平均加速度值為多少m／s 2？', '18 ', '72 ', '36 ', '10 ', '5。', '5');
INSERT INTO `data` VALUES (665, 28, '車子的初速度為36 km／h，加速度為2 m／s2，經過10 秒後速度變為多少 m／s？', '56 ', '20 ', '30 ', '10 ', '38。', '3');
INSERT INTO `data` VALUES (666, 28, '高速公路上一輛遊覽車以50.0 m／s 之等速度行駛，離收費站500 公尺處時司機踩煞車恰於收票口停車付費。若車子作等加速運動，請問其加速度大小是多少？', '5 ', '0.2 ', '8 ', '4 ', '2.5 m／s 2。', '5');
INSERT INTO `data` VALUES (667, 28, '某物以10 m／s 向西運動經5 秒後變成20 m／s 向東，則其平均加速度為：', '4 m／s 2 向東 ', '4 m／s 2 向西 ', '6 m／s 2 向東 ', '6 m／s 2 向西。', '', '3');
INSERT INTO `data` VALUES (668, 28, '一輛車子作等加速直線運動，若初速度為10 m／s，經過300 m 後，車速變為20 m／s，則車子的加速度應為多少m／s2？', '0.1 ', '0.2 ', '0.3 ', '0.4 ', '0.5。', '5');
INSERT INTO `data` VALUES (669, 28, '鐵路局早晨由新竹發出的通勤列車，開到中壢需時45分鐘。若新竹站與中壢站的距離為60公里，則該列火車的平均速率為 ', '40 ', '50 ', '60 ', '70 ', '80公里／時。', '5');
INSERT INTO `data` VALUES (670, 28, '下列何者不是向量 ', '位移 ', '加速度 ', '力 ', '速率。', '', '4');
INSERT INTO `data` VALUES (671, 28, '下列運動何者之平均速率等於瞬時速率？ ', '樹上落下的蘋果 ', '百米競賽中的選手 ', '繞地球等速運轉的人造衛星 ', '擺動中的單擺。', '', '3');
INSERT INTO `data` VALUES (672, 28, '兩輛摩托車以等速度相向行駛，已知兩車車速分別為12(m/s)與8(m/s)。若在某時刻兩車間的距離為100(m)，則再經幾秒後兩車發生相撞？ ', '1 ', '2 ', '4 ', '5 (s)。', '', '4');
INSERT INTO `data` VALUES (673, 28, '某人沿著半徑為52 m的圓形跑道繞半圈，花了40秒，則其平均速度大小為 ', '2.6 m/s ', '4.08 m/s ', '1.3 m/s ', '8.16 m/s ', '5.2 m/s', '1');
INSERT INTO `data` VALUES (674, 28, '某船沿河順流而下的航速為24公里／小時，逆流而上的航速為6公里／小時，船沿此河往返一趟，其 平均速率為若干公里／小時？ ', ' 0 ', ' 6 ', ' 12 ', ' 16 ', ' 18。', '4');
INSERT INTO `data` VALUES (675, 28, '某船沿河順流而下的航速為24公里／小時，逆流而上的航速為6公里／小時，船沿此河往返一趟，其 平均速度為若干公里／小時？ ', ' 0 ', ' 6 ', ' 12 ', ' 16 ', ' 18。', '1');
INSERT INTO `data` VALUES (676, 28, '下面哪一個單位表示加速度 ', '公尺／秒 ', '秒／公尺2 ', '公尺2／秒 ', '公尺／秒2。', '', '4');
INSERT INTO `data` VALUES (677, 28, '下列何者的方向和其他者不同 ', '力 ', '速度 ', '速度變化量 ', '加速度', '', '2');
INSERT INTO `data` VALUES (678, 28, '相同質量的鋼球、鋁球，鋼球以5v、鋁球以v的速度發生正向彈性碰撞，下列敘述何者正確？　', '鋁球受到撞擊力的量值是鋼球的五倍　', '鋁球動量改變量的量值是鋼球的五倍　', '鋁球速度改變量的量值是鋼球的五倍　', '鋁球動能改變量的量值是鋼球的五倍　', '以上皆非', '5');
INSERT INTO `data` VALUES (679, 28, '質量為m1的質點以相同速度v1與原靜止、質量為m2的質點作正向彈性碰撞。則下列哪一種情況最有可能使m2碰撞後的速度最大？　', '小明在練習籃球運球，籃球(m1)撞擊地球(m2)　', '小明在練習羽球殺球，羽球(m1)打到小王(m2)　', '小明在打撞球，母球(m1)撞到九號球(m2)　', '小明在打乒乓球，乒乓球(m1)打到球拍(m2)　', '小明坐公車，公車(m1)正面撞上停在路旁的腳踏車(m2)(假設彈性碰撞)', '5');
INSERT INTO `data` VALUES (680, 28, 'A、B兩物體發生相向碰撞，碰撞後A、B兩物體皆朝B原本運動方向運動，則下列敘述何者正確？　', ' A的質量一定比B小　', '碰撞前，A的動能一定比B大　', '碰撞前，A的動能一定比B小　', '碰撞前，A的動量量值一定比B大　', '碰撞前，A的動量量值一定比B小', '5');
INSERT INTO `data` VALUES (681, 28, '質量3.0 kg的A球以4.0 m／s的速度向右運動，與另一個質量為5.0 kg靜止的B球作正面彈性碰撞，求碰撞前系統的總動量為何？　', ' 0　', ' 3　', ' 4　', ' 12　', ' 20　kg．m／s', '4');
INSERT INTO `data` VALUES (682, 28, '質量m的A物體，以速度v與靜止的B物體作彈性碰撞，A物體在撞後以速度反方向運動，則物體B的質量為何？　', ' m　', ' m　', ' m　', ' 2m　', ' 2m', '4');
INSERT INTO `data` VALUES (683, 28, '質量m1的物體以速度v與質量m2的靜止物體作正向彈性碰撞，若m1＜m2，則碰撞後m1的速度不可能為　', '－v　', '－v　', '－v　', '－v　', '－2v', '5');
INSERT INTO `data` VALUES (684, 28, '質量M的A物，沿光滑水平面以速度v撞擊質量2M的靜止B物，發生正面彈性碰撞後，A物的動能變為原本的倍，則B物的速度為何？　', ' v　', ' v　', ' v　', '－v　', '－v', '3');
INSERT INTO `data` VALUES (685, 28, '質量3.0 kg的A球以4.0 m／s的速度向右運動，與另一個質量為5.0 kg、速度2.0 m／s向右運動的B球作正面彈性碰撞，求碰撞前系統的總動能為多少焦耳？　', ' 17　', ' 34　', ' 68　', ' 90　', ' 200　焦耳', '2');
INSERT INTO `data` VALUES (686, 28, 'm1＝2 kg以10 m／s向東運動，m2＝3 kg以5 m／s向西運動，兩者相向發生正向彈性碰撞，則碰撞前在質心上的觀察者看到m1的速度為多少m／s？　', ' 3　', ' 9　', ' 10　', ' 11　', ' 17　m／s', '2');
INSERT INTO `data` VALUES (687, 28, '質量不相等的兩物體作完全彈性碰撞，在此過程中，兩物體的哪種物理量大小必不相等？　', '所受碰撞的力　', '動量的變化量　', '速度的變化量　', '動能在碰撞前後的變化量　', '碰撞所經歷的時間', '3');
INSERT INTO `data` VALUES (688, 28, '兩物體發生碰撞，若從質量中心來看，關於碰撞前後兩物體相對質心速度的敘述，下列何者正確？　', '兩物體對質心的速度大小維持不變　', '兩物體對質心的速度大小與質量成正比，但方向相反　', '兩物體對質心的速度大小與質量成正比，但方向相同　', '兩物體對質心的速度大小與質量成反比，但方向相反　', '兩物體對質心的速度大小與質量成反比，但方向相同', '4');
INSERT INTO `data` VALUES (689, 28, '某物作自由落體運動，若不考慮空氣阻力，則2 秒內的位移與第2 秒內的位移量值比為何？', '1：4 ', '3：4 ', '1：2 ', '4：1 ', '4：3。', '5');
INSERT INTO `data` VALUES (690, 28, '若一運動體，速率隨時間變大，但速度方向沒有改變，則可知：', '物體作等加速度運動 ', '加速度與速度同方向 ', '加速度量值隨時間變大 ', '加速度量值隨時間變小。', '', '2');
INSERT INTO `data` VALUES (691, 28, '跑車由靜止加速至90 公里╱小時只需10 秒鐘，則平均加速度為何？', '9 ', '15 ', '2.5 ', '1.5 公尺╱秒2 。', '', '3');
INSERT INTO `data` VALUES (692, 28, '一物體若沿著圓周運動，而速率始終保持定值，稱為等速率圓周運動，由此可知：', '物體沒有加速度 ', '加速度為一定值 ', '加速度時時與速度垂直 ', '加速度時時與速度平行。', '', '3');
INSERT INTO `data` VALUES (693, 28, '已知加速度對速度的影響隨兩者的夾角大小不同而不同，若把加速度分解為與速度方向平行的分量aT (切線加速度)及與速度方向垂直的分量aN (法線加速度)，則等速率圓周運動過程，何者正確？', 'aN＝0、aT≠0 ', 'aN≠0、aT＝0 ', 'aN≠0、aT≠0 ', 'aN＝0、aT＝0。', '', '2');
INSERT INTO `data` VALUES (694, 28, '某物體運動位置(X)與時間(t)關係為：X＝4t＋20，如果位置以公尺為單位，時間以秒為單位，則物體在1.1 秒到3.6 秒間的平均速度為何？', '0 公尺／秒 ', '4 公尺／秒 ', '5 公尺／秒 ', '20 公尺／秒', '', '2');
INSERT INTO `data` VALUES (695, 28, '一顆小球自空中靜止落下，經過5 秒後落地，假設摩擦力可以忽略，重力加速度為10 公尺／秒2，則下列敘述何者正確？', '小球全程的平均速度為25 公尺／秒 ', '小球全程的總位移為50 公尺 ', '全程的平均加速度為2 公尺／秒2 ', '第3 秒時的瞬時速度為15 公尺／秒。', '', '1');
INSERT INTO `data` VALUES (696, 28, '已知一質點的位移量值為12 公尺，則其路徑長不可能是下面哪一數值？', '6 公尺 ', '12 公尺 ', '13 公尺 ', '15 公尺 ', '20 公尺。', '1');
INSERT INTO `data` VALUES (697, 28, '已知一質點的路徑長為12 公尺，則其位移量值不可能是下面哪一數值？', '6 公尺 ', '8 公尺 ', '9 公尺 ', '12 公尺 ', '16 公尺。', '5');
INSERT INTO `data` VALUES (698, 28, '下列有關位移與路徑長的敘述，何者正確？', '位移有方向性，路徑長無方向性 ', '位移與路徑長都有方向性 ', '位移無方向性，路徑長有方向性 ', '位移與路徑長都無方向性 ', '直線運動時，位移與路徑長為相同的物理量。', '1');
INSERT INTO `data` VALUES (699, 28, '下列有關位置、位移與路徑長的單位之敘述，何者正確？', '位移與位置單位相同，與路徑長不同 ', '位移與路徑長單位相同，與位置不同 ', '路徑長與位置單位相同，與位移不同 ', '位移、位置與路徑長的單位都一樣 ', '位移、位置與路徑長的單位都不相同。', '4');
INSERT INTO `data` VALUES (700, 28, '設火車由靜止開始以等加速行駛全程的 1／6，隨後改以等速v(亦為全程中的最大速度)行駛，最後以等減速行駛全程的 1／4 而停於次站，則此車之平均速度量值為v 的', '2/3', '11/6', '12/11', '12/17', '11/12倍。', '4');
INSERT INTO `data` VALUES (701, 28, '一列車沿直線由靜止起自甲站開往乙站，其最初之 1／8 行程以等加速度行駛，最後之 1／8行程則以等減速度行駛而停於乙站，中間之行程為等速度行駛。若此列車行駛時的最大速度為vM，則此列車行駛全程的平均速度為', '4/5VM ', '4/3VM ', '7/4VM ', '3/5VM ', '2VM。', '1');
INSERT INTO `data` VALUES (702, 28, '汽車在全程前半段時速50 公里，已知全程平均時速60 公里，問後半段時速多少公里？', '70 ', '75 ', '80 ', '85 ', '90。', '2');
INSERT INTO `data` VALUES (703, 28, '一直線運動質點的位置與時間t 的關係為x＝－t2＋4t(單位：SI 制)，則質點於前4 s 內的平均速度量值為若干m／s？', '4 ', '－4 ', '0 ', '－8 ', '8。', '3');
INSERT INTO `data` VALUES (704, 28, '光滑長斜面上，甲物體從頂端由靜止開始自由下滑，每間隔1 秒，另有乙、丙、丁物體也從同一位置依序由靜止自由下滑。則當丁物體開始下滑的瞬間，甲、乙的距離S1，丙、丁的距離S2，則S1：S2 =？', '2：1 ', '4：1 ', '3：1 ', '5：1 ', '6：1。', '4');
